'use strict';
(()=>{
 const data=window.LAB_CONTENT||{profiles:[],publications:[],members:[],news:[],events:[],gallery:[],projects:[]};
 const $=(q)=>document.querySelector(q);
 const $$=(q)=>[...document.querySelectorAll(q)];
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 function safeURL(value,{relative=false,mail=false}={}){try{const u=new URL(String(value),location.href);if(u.protocol==='https:'||u.protocol==='http:'||(mail&&u.protocol==='mailto:'))return u.href;if(relative&&!/^[a-z]+:/i.test(value)&&!String(value).startsWith('//'))return value;}catch{}return '';}
 function link(label,url,cls){const a=el('a',label,cls),safe=safeURL(url,{relative:true,mail:true});if(safe){a.href=safe;if(/^https?:/i.test(safe)&&new URL(safe).origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';}}return a;}
 function empty(target,title,message){if(!target)return;const box=el('div',null,'empty');box.append(el('h3',title),el('p',message));target.append(box);}
 const menu=$('.menu-toggle');menu?.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));$('#main-nav').classList.toggle('open',!expanded);});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu){menu.setAttribute('aria-expanded','false');$('#main-nav').classList.remove('open');}});
 const top=$('.back-top');if(top){addEventListener('scroll',()=>{top.hidden=scrollY<600;},{passive:true});top.addEventListener('click',()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));}
 $$('[data-profiles]').forEach(target=>{(data.profiles||[]).forEach(p=>{const a=link(p.name,p.url,'profile');a.setAttribute('aria-label',p.name+' profile of Dr. Rahul Pandey (opens in a new tab)');const img=el('img');img.src='assets/icons/'+p.icon+'.svg';img.alt='';a.prepend(img);target.append(a);});});
 function doiURL(raw){let s=String(raw||'').trim().replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'').replace(/^doi:\s*/i,'');return /^10\.\d{4,9}\/\S+$/i.test(s)?'https://doi.org/'+encodeURI(s).replace(/#/g,'%23').replace(/\?/g,'%3F'):'';}
 const included=(data.publications||[]).filter(p=>p.nitDelhiAffiliation===true);
 function citation(p){return [p.authors,p.title,p.journal||p.venue,p.year,p.doi].filter(Boolean).join('. ')+'.';}
 function bibtex(items){const esc=s=>String(s||'').replace(/[{}\\]/g,' ').replace(/[\r\n]/g,' ');return items.map((p,i)=>`@${p.type==='Conference paper'?'inproceedings':'article'}{pandey${p.year||''}_${i+1},\n  title = {${esc(p.title)}},\n  author = {${esc(p.authors)}},\n  journal = {${esc(p.journal||p.venue)}},\n  year = {${esc(p.year)}},\n  doi = {${esc(String(p.doi||'').replace(/^https?:\/\/doi.org\//i,''))}}\n}`).join('\n\n');}
 function download(text,name,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=link('',u);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 const pubList=$('#publication-list');let visiblePubs=included;
 if(pubList){const year=$('#pub-year');[...new Set(included.map(p=>String(p.year)).filter(y=>/^\d{4}$/.test(y)))].sort().reverse().forEach(y=>{const o=el('option',y);o.value=y;year.append(o);});
 function renderPubs(){const term=$('#pub-search').value.trim().toLowerCase(),yv=year.value,tv=$('#pub-type').value;visiblePubs=included.filter(p=>(yv==='all'||String(p.year)===yv)&&(tv==='all'||p.type===tv)&&[p.title,p.authors,p.journal,p.venue,p.doi,...(p.tags||[])].join(' ').toLowerCase().includes(term)).sort((a,b)=>Number(b.year)-Number(a.year));pubList.replaceChildren();$('#pub-count').textContent=included.length?`${visiblePubs.length} of ${included.length} publications`:'Publication collection being prepared';$('#export-bib').disabled=!visiblePubs.length;
 if(!visiblePubs.length){empty(pubList,included.length?'No matching publications':'NIT Delhi publications coming soon',included.length?'Try another keyword, year or publication type.':'The curated list of papers carrying NIT Delhi affiliation will be added here.');return;}
 visiblePubs.forEach(p=>{const card=el('article',null,'publication'),info=el('div');card.append(el('div',p.year,'pub-year'),info);info.append(el('h3',p.title),el('p',p.authors),el('p',[p.journal||p.venue,p.volume,p.pages,p.type].filter(Boolean).join(' · ')));const actions=el('div',null,'pub-actions'),doi=doiURL(p.doi);if(doi)actions.append(link('Read via DOI ↗',doi));if(p.url&&safeURL(p.url))actions.append(link('Publication ↗',p.url));const copy=el('button','Copy citation','citation-copy');copy.addEventListener('click',async()=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(citation(p));copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy citation',1800);}catch{const t=el('textarea',citation(p));t.setAttribute('aria-label','Citation text');t.readOnly=true;actions.append(t);t.focus();t.select();copy.textContent='Citation ready to copy';}});actions.append(copy);info.append(actions);pubList.append(card);});}
 ['#pub-search','#pub-year','#pub-type'].forEach(q=>$(q).addEventListener(q==='#pub-search'?'input':'change',renderPubs));$('#export-bib').addEventListener('click',()=>download(bibtex(visiblePubs),'ASMD_Lab_Publications.bib','application/x-bibtex'));renderPubs();}
 const memberList=$('#member-list');let memberStatus='present';
 if(memberList){function renderMembers(){memberList.replaceChildren();const level=$('#member-level').value,levels=['Post-Doc','PhD','PG','UG'].filter(x=>level==='all'||x===level);let count=0;levels.forEach(group=>{const items=(data.members||[]).filter(m=>m.status===memberStatus&&m.level===group);if(!items.length)return;count+=items.length;const section=el('section',null,'member-group');section.append(el('h2',{'Post-Doc':'Postdoctoral researchers','PhD':'PhD scholars','PG':'Postgraduate students','UG':'Undergraduate students'}[group]));const grid=el('div',null,'people-grid');items.forEach(m=>{const a=el('article',null,'person-card');if(m.photo&&safeURL(m.photo,{relative:true})){const img=el('img');img.src=m.photo;img.alt=m.name;img.loading='lazy';a.append(img);}else a.append(el('div',m.name.split(' ').slice(0,2).map(x=>x[0]).join(''),'person-initials'));a.append(el('h3',m.name),el('p',m.topic||'Research interests to be added'),el('p',[m.period,m.programme].filter(Boolean).join(' · ')));if(m.currentPosition)a.append(el('p',m.currentPosition));if(m.profile&&safeURL(m.profile))a.append(link('Profile ↗',m.profile));grid.append(a);});section.append(grid);memberList.append(section);});if(!count)empty(memberList,'Member directory being prepared',`Confirmed ${memberStatus==='present'?'current':'past'} ${level==='all'?'UG, PG, PhD and postdoctoral':level} member profiles will be added here.`);}
 $$('[data-status]').forEach(b=>b.addEventListener('click',()=>{memberStatus=b.dataset.status;$$('[data-status]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderMembers();}));$('#member-level').addEventListener('change',renderMembers);renderMembers();}
 function formatDate(d){if(!d)return '';const date=new Date(d+'T00:00:00');return Number.isNaN(+date)?d:date.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});}
 function sorted(items){return [...items].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));}
 function updates(target,items,kind){if(!target)return;target.replaceChildren();if(!items.length){empty(target,kind==='news'?'Updates coming soon':'Events will be announced here',kind==='news'?'Research updates, achievements and announcements will appear here.':'Details of workshops, seminars and other research events will be added here.');return;}items.forEach(n=>{const a=el('article',null,'update'),time=el('time',formatDate(n.date));if(/^\d{4}-\d{2}-\d{2}$/.test(n.date||''))time.dateTime=n.date;a.append(time);const body=el('div');body.append(el('h3',n.title),el('p',n.summary));if(n.venue)body.append(el('p',n.venue));if(n.image&&safeURL(n.image,{relative:true})){const img=el('img');img.src=n.image;img.alt=n.imageAlt||n.title;img.loading='lazy';body.append(img);}if(n.url&&safeURL(n.url))body.append(link(kind==='news'?'Read more ↗':'Event details ↗',n.url,'text-link'));a.append(body);target.append(a);});}
 updates($('[data-home-news]'),sorted(data.news||[]).slice(0,3),'news');updates($('#news-list'),sorted(data.news||[]),'news');updates($('[data-home-events]'),sorted(data.events||[]).slice(0,3),'events');
 const eventList=$('#event-list');if(eventList){const now=new Date();const today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');function eventSubset(key){return sorted(data.events||[]).filter(e=>key==='all'||(key==='upcoming'?(e.endDate||e.date)>=today:(e.endDate||e.date)<today));}updates(eventList,eventSubset('all'),'events');$$('[data-events]').forEach(b=>b.addEventListener('click',()=>{$$('[data-events]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));updates(eventList,eventSubset(b.dataset.events),'events');}));}
 const gallery=$('#gallery-list'),dialog=$('#lightbox');if(gallery){function renderGallery(category){gallery.replaceChildren();const items=(data.gallery||[]).filter(i=>category==='all'||i.category===category);if(!items.length){empty(gallery,'Lab photographs coming soon','Photographs of lab activities, events and members will be added to this collection.');return;}const grid=el('div',null,'gallery-grid');items.forEach(g=>{if(!safeURL(g.image,{relative:true}))return;const btn=el('button',null,'gallery-card'),img=el('img');img.src=g.image;img.alt=g.alt||g.caption;img.loading='lazy';btn.append(img,el('span',g.caption));btn.addEventListener('click',()=>{dialog.querySelector('img').src=g.image;dialog.querySelector('img').alt=g.alt||g.caption;dialog.querySelector('p').textContent=g.caption;dialog.showModal();});grid.append(btn);});gallery.append(grid);}$$('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{$$('[data-gallery]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderGallery(b.dataset.gallery);}));dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});renderGallery('all');}
 const projects=$('[data-projects]');if(projects){if(!(data.projects||[]).length)empty(projects,'Project details coming soon','Confirmed research project summaries, funding information and collaborators will be listed here.');else(data.projects||[]).forEach(p=>{const a=el('article',null,'callout');a.append(el('h3',p.title),el('p',p.summary));if(p.funder)a.append(el('p',p.funder));projects.append(a);});}
 window.LAB_UTILS={doiURL,citation,bibtex};
})();
