'use strict';
(()=>{
 const data=window.LAB_CONTENT||{profiles:[],publications:[],members:[],news:[],events:[],gallery:[],projects:[]};
 const $=(q)=>document.querySelector(q);
 const $$=(q)=>[...document.querySelectorAll(q)];
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 function safeURL(value,{relative=false,mail=false}={}){try{const u=new URL(String(value),location.href);if(u.protocol==='https:'||u.protocol==='http:'||(mail&&u.protocol==='mailto:'))return u.href;if(relative&&!/^[a-z]+:/i.test(value)&&!String(value).startsWith('//'))return value;}catch{}return '';}
 function link(label,url,cls){const a=el('a',label,cls),safe=safeURL(url,{relative:true,mail:true});if(safe){a.href=safe;if(/^https?:/i.test(safe)&&new URL(safe).origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';}}return a;}
 function empty(target,title,message){if(!target)return;const box=el('div',null,'empty');box.append(el('h3',title),el('p',message));target.append(box);}
 const menu=$('.menu-toggle');menu?.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));$('#main-nav').classList.toggle('open',!expanded);});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu){menu.setAttribute('aria-expanded','false');$('#main-nav').classList.remove('open');}});
 const top=$('.back-top');if(top){addEventListener('scroll',()=>{top.hidden=scrollY<600;},{passive:true});top.addEventListener('click',()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));}
 const facultyProfiles={basu:[{name:'LinkedIn',icon:'linkedin',url:'https://www.linkedin.com/in/rikmantra-basu-82074933a/'},{name:'Scopus',icon:'scopus',url:'https://www.scopus.com/authid/detail.uri?authorId=35271434600'},{name:'Google Scholar',icon:'scholar',url:'https://scholar.google.com/citations?user=LLKMCtcAAAAJ&hl=en'}]};
 $$('[data-profiles]').forEach(target=>{const basu=target.dataset.profiles==='basu',name=basu?'Dr. Rikmantra Basu':'Dr. Rahul Pandey',profiles=basu?facultyProfiles.basu:(data.profiles||[]);profiles.forEach(p=>{const a=link(p.name,p.url,'profile');a.setAttribute('aria-label',p.name+' profile of '+name+' (opens in a new tab)');const img=el('img');img.src='assets/icons/'+p.icon+'.svg';img.alt='';a.prepend(img);target.append(a);});});
 function doiURL(raw){let s=String(raw||'').trim().replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'').replace(/^doi:\s*/i,'');return /^10\.\d{4,9}\/\S+$/i.test(s)?'https://doi.org/'+encodeURI(s).replace(/#/g,'%23').replace(/\?/g,'%3F'):'';}
 const included=(data.publications||[]).filter(p=>p.nitDelhiAffiliation===true);
 const dashboard={publications:{items:included,note:'Papers carrying NIT Delhi affiliation'},members:{items:(data.members||[]).filter(m=>m.status==='present'),note:'UG · PG · PhD · Post-Docs'},projects:{items:data.projects||[],note:'Listed research projects'}};
 Object.entries(dashboard).forEach(([key,entry])=>{const value=$('[data-dashboard="'+key+'"]'),note=$('[data-dashboard-note="'+key+'"]');if(value&&entry.items.length){value.textContent=String(entry.items.length);if(note)note.textContent=entry.note;}});

 function citation(p){return [p.authors,p.title,p.journal||p.venue,p.year,p.doi].filter(Boolean).join('. ')+'.';}
 function bibtex(items){const esc=s=>String(s||'').replace(/[{}\\]/g,' ').replace(/[\r\n]/g,' ');return items.map((p,i)=>{const fields={title:p.title,author:p.bibtexAuthors||p.authors,journal:p.journal||p.venue,year:p.year,volume:p.volume,number:p.issue,pages:p.pages||p.articleNumber,doi:String(p.doi||'').replace(/^https?:\/\/doi.org\//i,'')};return '@'+(p.type==='Conference paper'?'inproceedings':'article')+'{pandey'+(p.year||'')+'_'+(i+1)+',\n'+Object.entries(fields).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([k,v])=>'  '+k+' = {'+esc(v)+'}').join(',\n')+'\n}';}).join('\n\n');}
 function download(text,name,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=link('',u);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 const cloudStop=new Set('a an and are as at be been by for from in into is its of on or that the their these this through to using via was were with without study studies investigation investigations analysis effect effects based enhanced enhancement high efficient efficiency novel performance approach evaluation comparative numerical theoretical experimental influence impact improved improvement optimization optimised optimized towards toward'.split(' '));
 const cloudForms={cells:'cell',materials:'material',devices:'device',perovskites:'perovskite',simulations:'simulation',interfaces:'interface',layers:'layer',structures:'structure',properties:'property',absorbers:'absorber',heterojunctions:'heterojunction',photovoltaics:'photovoltaic',nanoparticles:'nanoparticle'};
 function cloudTerms(items){const counts=new Map();items.forEach(p=>{const terms=new Set();const words=[p.title,...(p.tags||[])].join(' ').toLowerCase().match(/[a-z][a-z0-9]*/g)||[];words.forEach(word=>{const term=cloudForms[word]||word;if(term.length>2&&!cloudStop.has(term))terms.add(term);});terms.forEach(term=>counts.set(term,(counts.get(term)||0)+1));});return [...counts].map(([term,count])=>({term,count})).sort((a,b)=>b.count-a.count||a.term.localeCompare(b.term)).slice(0,24);}
 function wordCloudLayout(terms,measure){const width=820,height=300,maximum=terms[0]?.count||1;let best=[];for(let attempt=0;attempt<15;attempt++){const placed=[],scale=Math.pow(.93,attempt);for(const entry of terms){const size=Math.max(12,Math.round((14+28*Math.sqrt(entry.count/maximum))*scale)),w=measure(entry.term,size)+12,h=size*1.3+8;let result;for(let step=0;step<4000;step++){const angle=step*.23,radius=4.4*Math.sqrt(step),x=width/2+radius*Math.cos(angle)*2.1-w/2,y=height/2+radius*Math.sin(angle)-h/2;if(x<12||y<12||x+w>width-12||y+h>height-12)continue;if(placed.some(b=>x<b.x+b.w&&x+w>b.x&&y<b.y+b.h&&y+h>b.y))continue;result={...entry,size,x,y,w,h};break;}if(result)placed.push(result);}if(placed.length>best.length)best=placed;if(placed.length===terms.length)return placed;}return best;}
 function renderCloud(target,items){if(!target)return;target.replaceChildren();const terms=cloudTerms(items);if(!terms.length){empty(target,'No word cloud available','Select publications with titles or author keywords to view research terms.');return;}
 const ctx=el('canvas').getContext?.('2d'),measure=(term,size)=>{if(ctx){ctx.font=`600 ${size}px Arial`;return ctx.measureText(term).width;}return term.length*size*.65;},layout=wordCloudLayout(terms,measure),ns='http://www.w3.org/2000/svg',svgNode=(tag,attrs,text)=>{const node=document.createElementNS(ns,tag);Object.entries(attrs||{}).forEach(([k,v])=>node.setAttribute(k,String(v)));if(text!=null)node.textContent=text;return node;};
 const svg=svgNode('svg',{xmlns:ns,viewBox:'0 0 820 300',role:'img','aria-label':'Research terms sized by the number of publications mentioning them'});svg.append(svgNode('title',{},'ASMD Lab research word cloud'),svgNode('rect',{width:820,height:300,fill:'#f7fbfe'}));const colours=['#11395b','#236a9b','#197987','#416d88','#2c506b'];layout.forEach((word,i)=>{const text=svgNode('text',{x:word.x+word.w/2,y:word.y+word.h/2,'text-anchor':'middle','dominant-baseline':'central','font-family':'Arial, sans-serif','font-weight':600,'font-size':word.size,fill:colours[i%colours.length]},word.term);text.append(svgNode('title',{},`${word.term}: ${word.count} publications`));svg.append(text);});
 const toolbar=el('div',null,'cloud-toolbar'),save=el('button','Download SVG','outline');save.type='button';save.addEventListener('click',()=>download(new XMLSerializer().serializeToString(svg),'ASMD_Lab_Research_Word_Cloud.svg','image/svg+xml'));toolbar.append(el('p',`Based on ${items.length} ${items.length===1?'publication':'publications'}`),save);const figure=el('figure',null,'cloud-figure');figure.append(svg,el('figcaption','Top research terms in publication titles and author keywords. Larger words appear in more papers; each term is counted once per paper.'));
 const frequencies=el('details',null,'cloud-frequencies'),table=el('table'),head=el('thead'),row=el('tr');row.append(el('th','Research term'),el('th','Publications'));head.append(row);table.append(head);const body=el('tbody');terms.forEach(word=>{const r=el('tr');r.append(el('td',word.term),el('td',word.count));body.append(r);});table.append(body);frequencies.append(el('summary','View term frequencies'),table);target.append(toolbar,figure,frequencies);}
 renderCloud($('[data-cloud="home"]'),included);
 const pubList=$('#publication-list');let visiblePubs=included;
 if(pubList){const year=$('#pub-year');[...new Set(included.map(p=>String(p.year)).filter(y=>/^\d{4}$/.test(y)))].sort().reverse().forEach(y=>{const o=el('option',y);o.value=y;year.append(o);});
 function renderPubs(){const term=$('#pub-search').value.trim().toLowerCase(),yv=year.value,tv=$('#pub-type').value;visiblePubs=included.filter(p=>(yv==='all'||String(p.year)===yv)&&(tv==='all'||p.type===tv)&&[p.title,p.authors,p.journal,p.venue,p.doi,...(p.tags||[])].join(' ').toLowerCase().includes(term)).sort((a,b)=>Number(b.year)-Number(a.year));pubList.replaceChildren();$('#pub-count').textContent=included.length?`${visiblePubs.length} of ${included.length} publications`:'Publication collection being prepared';$('#export-bib').disabled=!visiblePubs.length;
 renderCloud($('[data-cloud="publications"]'),visiblePubs);
 if(!visiblePubs.length){empty(pubList,included.length?'No matching publications':'Lab Publications coming soon',included.length?'Try another keyword, year or publication type.':'The curated list of papers carrying NIT Delhi affiliation will be added here.');return;}
 visiblePubs.forEach(p=>{const card=el('article',null,'publication'),info=el('div');card.append(el('div',p.year,'pub-year'),info);info.append(el('h3',p.title),el('p',p.authors),el('p',[p.journal||p.venue,p.volume?'Vol. '+p.volume:'',p.issue?'Issue '+p.issue:'',p.pages?'pp. '+p.pages:(p.articleNumber?'Article '+p.articleNumber:''),p.type].filter(Boolean).join(' · ')));if(p.publicationStage==='Article in press')info.append(el('span','Article in press','publication-stage'));const actions=el('div',null,'pub-actions'),doi=doiURL(p.doi);if(doi)actions.append(link('Read via DOI ↗',doi));if(p.url&&safeURL(p.url))actions.append(link('Publication ↗',p.url));const copy=el('button','Copy citation','citation-copy');copy.addEventListener('click',async()=>{try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(citation(p));copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy citation',1800);}catch{const t=el('textarea',citation(p));t.setAttribute('aria-label','Citation text');t.readOnly=true;actions.append(t);t.focus();t.select();copy.textContent='Citation ready to copy';}});actions.append(copy);info.append(actions);pubList.append(card);});}
 ['#pub-search','#pub-year','#pub-type'].forEach(q=>$(q).addEventListener(q==='#pub-search'?'input':'change',renderPubs));$('#export-bib').addEventListener('click',()=>download(bibtex(visiblePubs),'ASMD_Lab_Publications.bib','application/x-bibtex'));renderPubs();}
 const memberList=$('#member-list');let memberStatus='present';
 if(memberList){function renderMembers(){memberList.replaceChildren();const level=$('#member-level').value,levels=['Post-Doc','PhD','PG','UG'].filter(x=>level==='all'||x===level);let count=0;levels.forEach(group=>{const items=(data.members||[]).filter(m=>m.status===memberStatus&&m.level===group);if(!items.length)return;count+=items.length;const section=el('section',null,'member-group');section.append(el('h2',{'Post-Doc':'Postdoctoral researchers','PhD':'PhD scholars','PG':'Postgraduate students','UG':'Undergraduate students'}[group]));const grid=el('div',null,'people-grid');items.forEach(m=>{const a=el('article',null,'person-card');if(m.photo&&safeURL(m.photo,{relative:true})){const img=el('img');img.src=m.photo;img.alt=m.name;img.loading='lazy';a.append(img);}else a.append(el('div',m.name.split(' ').slice(0,2).map(x=>x[0]).join(''),'person-initials'));a.append(el('h3',m.name),el('p',m.topic||'Research interests to be added'),el('p',[m.period,m.programme].filter(Boolean).join(' · ')));if(m.currentPosition)a.append(el('p',m.currentPosition));if(m.profile&&safeURL(m.profile))a.append(link('Profile ↗',m.profile));grid.append(a);});section.append(grid);memberList.append(section);});if(!count)empty(memberList,'Member directory being prepared',`Confirmed ${memberStatus==='present'?'current':'past'} ${level==='all'?'UG, PG, PhD and postdoctoral':level} member profiles will be added here.`);}
 $$('[data-status]').forEach(b=>b.addEventListener('click',()=>{memberStatus=b.dataset.status;$$('[data-status]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderMembers();}));$('#member-level').addEventListener('change',renderMembers);renderMembers();}
 const internList=$('#intern-list');let internStatus='completed';
 if(internList){function renderInterns(){internList.replaceChildren();const interns=(data.interns||[]).filter(i=>i.status===internStatus);if(!interns.length){empty(internList,'Internship directory being prepared',internStatus==='completed'?'External students who completed an internship at ASMD Lab will be listed here.':'External students currently undertaking an internship at ASMD Lab will be listed here.');return;}const grid=el('div',null,'people-grid');interns.forEach(i=>{const card=el('article',null,'person-card');if(i.photo&&safeURL(i.photo,{relative:true})){const photo=el('img');photo.src=i.photo;photo.alt=i.name;photo.loading='lazy';card.append(photo);}else card.append(el('div',i.name.split(' ').slice(0,2).map(n=>n[0]).join(''),'person-initials'));card.append(el('h3',i.name),el('p',i.institution||'Home institution to be added','intern-institution'),el('p',[i.programme,i.period].filter(Boolean).join(' · ')),el('p',i.topic||'Internship project to be added'));if(i.profile&&safeURL(i.profile))card.append(link('Profile ↗',i.profile));grid.append(card);});internList.append(grid);}$$('[data-intern-status]').forEach(button=>button.addEventListener('click',()=>{internStatus=button.dataset.internStatus;$$('[data-intern-status]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderInterns();}));renderInterns();}
 function formatDate(d){if(!d)return '';const date=new Date(d+'T00:00:00');return Number.isNaN(+date)?d:date.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});}
 function sorted(items){return [...items].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));}
 function sortedNews(items){return [...items].sort((a,b)=>{const ao=Number.isFinite(a.displayOrder)?a.displayOrder:Infinity,bo=Number.isFinite(b.displayOrder)?b.displayOrder:Infinity;return ao===bo?String(b.date||'').localeCompare(String(a.date||'')):ao-bo;});}
 function linkedinURL(raw,{embed=false}={}){try{const u=new URL(String(raw));if(u.protocol!=='https:'||!['linkedin.com','www.linkedin.com'].includes(u.hostname)||u.username||u.password||u.port)return '';const path=decodeURIComponent(u.pathname);if(embed){if(!/^\/embed\/feed\/update\/urn:li:(activity|share|ugcPost):\d+\/?$/.test(path))return '';}else if(!/^\/(posts\/[^/]+|feed\/update\/urn:li:(activity|share|ugcPost):\d+)\/?$/.test(path))return '';return u.href;}catch{return '';}}
 function newsSource(n){if(n.source==='manual'||n.source==='linkedin')return n.source;return linkedinURL(n.linkedinUrl)||linkedinURL(n.url)||linkedinURL(n.linkedinEmbedUrl,{embed:true})?'linkedin':'manual';}
 const previewMode=window.LAB_PREVIEW===true||location.protocol==='file:';
 function postCard(n,post){const card=el('div',null,'linkedin-card'),header=el('div',null,'linkedin-card-header'),own=n.sourceAuthor==='Dr. Rahul Pandey';if(own){const image=el('img');image.src='assets/rahul-pandey.png';image.alt='Dr. Rahul Pandey';image.className='linkedin-author-photo';header.append(image);}else header.append(el('div',(n.sourceAuthor||'LinkedIn').split(' ').slice(0,2).map(s=>s[0]).join(''),'linkedin-author-initials'));const author=el('div',null,'linkedin-author');author.append(el('strong',n.sourceAuthor||'LinkedIn post'),el('span',own?'Assistant Professor · NIT Delhi':'Original post source'));header.append(author,link('LinkedIn ↗',post,'linkedin-source-link'));card.append(header);if(n.summary)card.append(el('p','Post summary','linkedin-summary-label'),el('p',n.summary,'linkedin-card-summary'));else card.append(el('p','Open the LinkedIn post to read this update.','linkedin-card-summary'));if(n.image&&safeURL(n.image,{relative:true})){const image=el('img');image.src=n.image;image.alt=n.imageAlt||n.title||'LinkedIn post image';image.loading='lazy';image.className='linkedin-post-image';card.append(image);}return card;}
 function renderNews(target,items,total){if(!target)return;target.replaceChildren();if(!items.length){empty(target,total?'No matching news':'Updates coming soon',total?'Try another source, topic or search keyword.':'Lab announcements and selected research posts from LinkedIn will appear here.');return;}items.forEach(n=>{const article=el('article',null,'update news-entry'),time=el('time',n.dateLabel||formatDate(n.date));if(/^\d{4}-\d{2}-\d{2}$/.test(n.date||''))time.dateTime=n.date;const post=linkedinURL(n.linkedinUrl)||linkedinURL(n.url),embed=linkedinURL(n.linkedinEmbedUrl,{embed:true}),body=el('div'),meta=el('div',null,'news-meta'),source=newsSource(n);meta.append(el('span',source==='linkedin'?'LinkedIn':'Lab news'));if(n.category||source==='manual')meta.append(el('span',n.category||'Announcements'));body.append(meta,el('h3',n.title||(source==='linkedin'?'LinkedIn post':'Lab news')));if(n.sourceAuthor)body.append(el('p','Original post: '+n.sourceAuthor+(n.sharedBy?' · Shared by '+n.sharedBy:''),'news-attribution'));
 if(embed&&previewMode){body.append(postCard(n,post||embed));}else if(embed){const visibleSummary=el('p',n.summary,'embed-visible-summary');if(n.summary)body.append(visibleSummary);const frameWrap=el('div',null,'linkedin-embed'),frame=el('iframe');frame.src=embed;frame.title=n.title?'LinkedIn full post: '+n.title:'LinkedIn post';frame.loading='lazy';frame.height=String(Math.min(2400,Math.max(380,Number(n.embedHeight)||1000)));frame.setAttribute('allowfullscreen','');frameWrap.append(frame);body.append(frameWrap);const toggle=el('button','Hide embedded post','embed-visibility');toggle.type='button';toggle.setAttribute('aria-expanded','true');toggle.addEventListener('click',()=>{frameWrap.hidden=!frameWrap.hidden;toggle.textContent=frameWrap.hidden?'Show embedded post':'Hide embedded post';toggle.setAttribute('aria-expanded',String(!frameWrap.hidden));});body.append(toggle);}else{if(n.summary)body.append(el('p',n.summary));if(n.image&&safeURL(n.image,{relative:true})){const image=el('img');image.src=n.image;image.alt=n.imageAlt||n.title||'LinkedIn post image';image.loading='lazy';body.append(image);}}
 const actions=el('div',null,'news-links');if(post)actions.append(link('View on LinkedIn ↗',post,'text-link'));if(n.url&&safeURL(n.url)&&n.url!==post)actions.append(link('Read more ↗',n.url,'text-link'));if(!post&&embed)actions.append(link('Open LinkedIn post ↗',embed,'text-link'));if(actions.children.length)body.append(actions);article.append(time,body);target.append(article);});}
 function renderEvents(target,items){
  if(!target)return;
  target.replaceChildren();
  if(!items.length){empty(target,'No events in this category','Choose All events or Past events to browse the workshop archive.');return;}
  items.forEach(n=>{
   const article=el('article',null,'update event-entry'),time=el('time',n.dateLabel||formatDate(n.date));
   if(n.id&&/^[a-z0-9-]+$/.test(n.id))article.id=n.id;
   if(/^\d{4}-\d{2}-\d{2}$/.test(n.date||''))time.dateTime=n.date;
   article.append(time);
   const body=el('div',null,'event-body'),layout=el('div',null,'event-layout'),info=el('div',null,'event-info');
   if(n.category)info.append(el('p',n.category,'eyebrow'));
   info.append(el('h3',n.title));
   if(n.summary)info.append(el('p',n.summary));
   const meta=el('dl',null,'event-meta');
   [['Location',n.venue],['Coordinator(s)',n.coordinators],['Organized by',n.organizedBy]].forEach(([label,value])=>{if(value){meta.append(el('dt',label),el('dd',value));}});
   if(meta.children.length)info.append(meta);
   const actions=el('div',null,'event-actions');
   if(n.url&&safeURL(n.url))actions.append(link(n.urlLabel||'Event details ↗',n.url,'text-link'));
   if(n.image&&safeURL(n.image,{relative:true}))actions.append(link('View event poster ↗',n.image,'text-link'));
   if(actions.children.length)info.append(actions);
   layout.append(info);
   if(n.image&&safeURL(n.image,{relative:true})){
    const poster=link('',n.image,'event-poster'),img=el('img');
    poster.setAttribute('aria-label','View poster for '+n.title+' (opens in a new tab)');
    img.src=n.image;img.alt=n.imageAlt||n.title;img.loading='lazy';img.decoding='async';
    poster.append(img);layout.append(poster);
   }
   body.append(layout);
   const paragraphs=Array.isArray(n.overview)?n.overview:typeof n.overview==='string'?[n.overview]:[],photos=Array.isArray(n.photos)?n.photos:[];
   if(paragraphs.length||photos.length){
    const details=el('details',null,'event-overview');
    details.append(el('summary',paragraphs.length&&photos.length?'Event overview and photographs':photos.length?'Event photographs':'Event overview'));
    paragraphs.forEach(p=>details.append(el('p',p)));
    if(photos.length){
     details.append(el('h4','Glimpses of the event'));
     const grid=el('div',null,'event-photos');
     photos.forEach((p,i)=>{
      if(!safeURL(p.image,{relative:true}))return;
      const figure=el('figure'),a=link('',p.image,'event-photo-link'),img=el('img');
      a.setAttribute('aria-label','Open photograph '+(i+1)+' from '+n.title+' (opens in a new tab)');
      img.src=p.image;img.alt=p.alt||n.title+' photograph '+(i+1);img.loading='lazy';img.decoding='async';
      a.append(img);figure.append(a,el('figcaption',p.caption||'Photograph '+(i+1)));grid.append(figure);
     });
     details.append(grid);
    }
    body.append(details);
   }
   article.append(body);target.append(article);
  });
 }
 function homeUpdate(target,items,kind){if(!target)return;target.replaceChildren();if(!items.length){empty(target,kind==='news'?'Updates coming soon':'No upcoming events listed',kind==='news'?'Research news and announcements will appear here.':'Check the Events tab for the full event archive.');return;}const n=items[0],article=el('article',null,'update');article.append(el('time',n.dateLabel||formatDate(n.date)));const body=el('div');body.append(el('h3',n.title||(kind==='news'&&newsSource(n)==='linkedin'?'LinkedIn post':'Lab update')));if(n.summary)body.append(el('p',n.summary));if(n.venue)body.append(el('p',n.venue));body.append(link(kind==='news'?'Read all news →':'View event details →',kind==='news'?'news.html':'events.html','text-link'));article.append(body);target.append(article);}
 const todayIndia=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
 const nextEvents=(data.events||[]).filter(e=>/^\d{4}-\d{2}-\d{2}$/.test(e.date||'')&&(e.endDate||e.date)>=todayIndia).sort((a,b)=>String(a.date).localeCompare(String(b.date)));
 homeUpdate($('[data-home-news]'),sortedNews(data.news||[]),'news');homeUpdate($('[data-home-events]'),nextEvents,'events');
 const newsList=$('#news-list');if(newsList){let source='all';function filterNews(){const term=($('#news-search')?.value||'').trim().toLowerCase(),category=$('#news-category')?.value||'all',all=data.news||[],items=sortedNews(all).filter(n=>(source==='all'||newsSource(n)===source)&&(category==='all'||(n.category||'Announcements')===category)&&[n.title,n.summary,n.category,...(n.tags||[])].join(' ').toLowerCase().includes(term));const count=$('#news-count');if(count)count.textContent=all.length?`${items.length} of ${all.length} news ${all.length===1?'entry':'entries'}`:'News collection being prepared';renderNews(newsList,items,all.length);}$$('[data-news-source]').forEach(b=>b.addEventListener('click',()=>{source=b.dataset.newsSource;$$('[data-news-source]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filterNews();}));$('#news-search')?.addEventListener('input',filterNews);$('#news-category')?.addEventListener('change',filterNews);filterNews();}
 const eventList=$('#event-list');if(eventList){const today=todayIndia;function eventSubset(key){return sorted(data.events||[]).filter(e=>key==='all'||(key==='upcoming'?(e.endDate||e.date)>=today:(e.endDate||e.date)<today));}renderEvents(eventList,eventSubset('all'));$$('[data-events]').forEach(b=>b.addEventListener('click',()=>{$$('[data-events]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderEvents(eventList,eventSubset(b.dataset.events));}));}
 const gallery=$('#gallery-list'),dialog=$('#lightbox');if(gallery){function renderGallery(category){gallery.replaceChildren();const items=(data.gallery||[]).filter(i=>category==='all'||i.category===category);if(!items.length){empty(gallery,'Lab photographs coming soon','Photographs of lab activities, events and members will be added to this collection.');return;}const grid=el('div',null,'gallery-grid');items.forEach(g=>{if(!safeURL(g.image,{relative:true}))return;const btn=el('button',null,'gallery-card'),img=el('img');img.src=g.image;img.alt=g.alt||g.caption;img.loading='lazy';btn.append(img,el('span',g.caption));btn.addEventListener('click',()=>{dialog.querySelector('img').src=g.image;dialog.querySelector('img').alt=g.alt||g.caption;dialog.querySelector('p').textContent=g.caption;dialog.showModal();});grid.append(btn);});gallery.append(grid);}$$('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{$$('[data-gallery]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderGallery(b.dataset.gallery);}));dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});renderGallery('all');}
 const projects=$('[data-projects]');if(projects){if(!(data.projects||[]).length)empty(projects,'Project details coming soon','Confirmed research project summaries, funding information and collaborators will be listed here.');else(data.projects||[]).forEach(p=>{const a=el('article',null,'callout');a.append(el('h3',p.title),el('p',p.summary));if(p.funder)a.append(el('p',p.funder));projects.append(a);});}
 window.LAB_UTILS={doiURL,citation,bibtex,cloudTerms,wordCloudLayout,linkedinURL,newsSource};
})();
