from pathlib import Path
import json
root=Path(__file__).parent
profiles=[
 {'name':'Scopus','icon':'scopus','url':'https://www.scopus.com/authid/detail.uri?authorId=56609687400'},
 {'name':'Web of Science','icon':'wos','url':'https://www.webofscience.com/wos/author/record/IAN-2528-2023'},
 {'name':'ResearchGate','icon':'rg','url':'https://www.researchgate.net/profile/Rahul-Pandey-3'},
 {'name':'LinkedIn','icon':'linkedin','url':'https://www.linkedin.com/in/rahul-pandey-%F0%9F%87%AE%F0%9F%87%B3-856a18183/'},
 {'name':'Google Scholar','icon':'scholar','url':'https://scholar.google.com/citations?hl=en&user=NMz9JVsAAAAJ'},
 {'name':'ORCID','icon':'orcid','url':'https://orcid.org/0000-0001-7766-3572'}]
data={'updated':'2026-10-08','profiles':profiles,'publications':[],'members':[],'news':[],'events':[],'gallery':[],'projects':[]}
if not (root/'content.js').exists():
 (root/'content.js').write_text('/* Shared website content. Update through ChatGPT or edit these records. */\nwindow.LAB_CONTENT = '+json.dumps(data,indent=2)+';\n')
icons=[('scopus','Sc','#df6e23'),('wos','WoS','#643f89'),('rg','RG','#008578'),('linkedin','in','#0a66c2'),('scholar','GS','#4285f4'),('orcid','iD','#70a12e')]
for name,label,color in icons:
 (root/'assets/icons'/f'{name}.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="{color}"/><text x="32" y="42" text-anchor="middle" fill="white" font-size="{23 if len(label)>2 else 29}" font-weight="700" font-family="Arial,sans-serif">{label}</text></svg>')
nav=[('index.html','Home'),('research.html','Research'),('publications.html','Publications'),('people.html','People'),('news.html','News'),('events.html','Events'),('gallery.html','Gallery')]
def header(active):
 return '<a class="skip" href="#main">Skip to content</a><div class="institution"><div class="wrap"><a href="https://nitdelhi.ac.in/" target="_blank" rel="noopener noreferrer">National Institute of Technology Delhi ↗</a><span>Department of Applied Sciences (Physics)</span></div></div><header><div class="wrap nav"><a class="brand" href="index.html"><img src="assets/nit-delhi-logo.png" alt="NIT Delhi emblem"><span>ASMD<span class="brand-light"> Lab</span><small>Materials · Devices · Discovery</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button><nav id="main-nav" aria-label="Main navigation">'+''.join(f'<a href="{url}"'+(' aria-current="page"' if url==active else '')+f'>{label}</a>' for url,label in nav)+'<a class="nav-contact" href="contact.html">Contact ↗</a></nav></div></header>'
def footer():
 return '''<footer><div class="wrap foot-grid"><div><a class="foot-brand" href="index.html">ASMD Lab</a><p>Advanced Semiconductor Materials and Devices Laboratory<br>Department of Applied Sciences (Physics)<br>National Institute of Technology Delhi</p></div><div><h3>Explore</h3><a href="people.html">Our people</a><a href="research.html#methods">Methods & tools</a><a href="contact.html#join">Join the lab</a></div><div><h3>Get in touch</h3><a href="mailto:rahulpandey@nitdelhi.ac.in">rahulpandey@nitdelhi.ac.in</a><a href="https://faculty.nitdelhi.ac.in/RahulPandey/profile" target="_blank" rel="noopener noreferrer">NIT Delhi faculty profile ↗</a><a href="https://ashm.nitdelhi.ac.in/" target="_blank" rel="noopener noreferrer">Department website ↗</a></div></div><div class="wrap foot-bottom"><span>© 2026 ASMD Lab · NIT Delhi</span><span>Research illustrations are conceptual, not photographs of lab facilities.</span></div></footer><button class="back-top" aria-label="Back to top" hidden>↑</button>'''
def intro(kicker,title,text):
 return f'<section class="page-intro"><div class="wrap"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="lead">{text}</p></div></section>'
def areas():
 return '''<div class="research-grid"><article><span class="num">01 / ENERGY</span><h3>Photovoltaics & solar cells</h3><p>Perovskite and tandem architectures, thin-film absorbers, interface engineering, and device performance optimisation.</p><div class="tags"><span>Perovskites</span><span>Tandems</span><span>SCAPS-1D</span></div></article><article><span class="num">02 / ELECTRONICS</span><h3>Semiconductor devices</h3><p>Device physics and modelling of field-effect transistors, nanoscale architectures, and semiconductor sensing devices.</p><div class="tags"><span>TFETs</span><span>FinFETs</span><span>TCAD</span></div></article><article><span class="num">03 / MATERIALS</span><h3>Computational materials</h3><p>Atomistic calculations of structural, electronic, optical, dielectric, and transport properties of emerging semiconductors.</p><div class="tags"><span>DFT</span><span>QuantumATK</span><span>Lead-free materials</span></div></article><article><span class="num">04 / SENSING</span><h3>Sensors & optoelectronics</h3><p>Semiconductor and nanoscale sensing concepts, biosensors, photodetectors, and coupled electronic and optical response.</p><div class="tags"><span>Biosensors</span><span>Photodetectors</span><span>Transport</span></div></article></div>'''
contents={}
contents['index.html']='''<section class="hero home-hero"><div class="wrap home-intro"><div><p class="eyebrow">ASMD LAB / NIT DELHI</p><h1>Advanced Semiconductor Materials and Devices Laboratory</h1><p class="lead">Materials, photovoltaics and semiconductor devices for energy, electronics and sensing.</p><div class="home-pi"><strong>Lab In-charge: Dr. Rahul Pandey</strong><span>Assistant Professor · Applied Sciences (Physics)</span><div class="profiles compact-profiles" data-profiles></div></div></div><figure class="home-art"><img src="assets/research-illustrations.jpg" alt="Conceptual semiconductor wafer, solar cell and atomic lattice" width="1254" height="1254"><figcaption>Conceptual research illustration</figcaption></figure></div></section><section class="home-dashboard"><div class="wrap"><div class="home-heading"><h2>Lab at a glance</h2><a class="text-link" href="research.html">Explore our research →</a></div><div class="dashboard-grid"><a class="dashboard-card" href="research.html"><span class="dashboard-label">Research themes</span><strong>4</strong><span class="dashboard-note">Materials · Energy · Electronics · Sensing</span><span class="dashboard-action">Research details ↗</span></a><a class="dashboard-card" href="publications.html"><span class="dashboard-label">NIT Delhi publications</span><strong data-dashboard="publications">—</strong><span class="dashboard-note" data-dashboard-note="publications">Collection being prepared</span><span class="dashboard-action">Publications & DOI links ↗</span></a><a class="dashboard-card" href="people.html"><span class="dashboard-label">Current members</span><strong data-dashboard="members">—</strong><span class="dashboard-note" data-dashboard-note="members">Directory being prepared</span><span class="dashboard-action">Present & past members ↗</span></a><a class="dashboard-card" href="research.html#projects"><span class="dashboard-label">Research projects</span><strong data-dashboard="projects">—</strong><span class="dashboard-note" data-dashboard-note="projects">Project details being prepared</span><span class="dashboard-action">Projects & collaborations ↗</span></a></div></div></section><section class="home-updates"><div class="wrap home-update-grid"><article class="home-update-panel"><div class="home-heading"><h2>Recent news</h2><a class="text-link" href="news.html">All news →</a></div><div data-home-news></div></article><article class="home-update-panel"><div class="home-heading"><h2>Next event</h2><a class="text-link" href="events.html">All events →</a></div><div data-home-events></div></article><aside class="home-connect"><p class="eyebrow">JOIN & COLLABORATE</p><h3>Connect with ASMD Lab</h3><p>Student projects, research opportunities and collaborations.</p><a class="button" href="contact.html#join">Contact the lab ↗</a></aside></div></section>'''
contents['research.html']=intro('OUR RESEARCH','Materials to device performance','Research across photovoltaics, semiconductor electronics and sensing, supported by computational methods and experimental studies.')+'''<section class="section"><div class="wrap">'''+areas()+'''</div></section><section class="section pale" id="methods"><div class="wrap"><p class="eyebrow">METHODS & TOOLS</p><h2>A connected modelling approach</h2><div class="methods"><article><span>01</span><h3>Atomistic & materials modelling</h3><p>Electronic structure, optical properties and charge transport.</p><strong>QuantumATK · Quantum ESPRESSO · DFT</strong></article><article><span>02</span><h3>Process & device simulation</h3><p>Device structures, carrier transport, interfaces and photovoltaic response.</p><strong>Silvaco Victory · SCAPS-1D · TCAD</strong></article><article><span>03</span><h3>Circuit analysis & optimisation</h3><p>Connecting device models to circuit behaviour and parameter optimisation.</p><strong>Cadence · SmartSpice · Data-driven methods</strong></article></div></div></section><section class="section" id="projects"><div class="wrap"><p class="eyebrow">PROJECTS & COLLABORATION</p><h2>Research projects</h2><div data-projects></div><div class="callout"><h3>Interested in a collaboration?</h3><p>Contact Dr. Rahul Pandey to discuss materials modelling, device simulation, experimental studies or joint research.</p><a class="text-link" href="contact.html">Contact the lab →</a></div></div></section>'''
contents['publications.html']=intro('RESEARCH OUTPUT','Publications','Journal papers and other research publications carrying NIT Delhi affiliation. Each listed paper links to its DOI when provided.')+'''<section class="section compact"><div class="wrap"><div class="filters"><label class="search-label">Search publications<input type="search" id="pub-search" placeholder="Title, author, journal or DOI"></label><label>Year<select id="pub-year"><option value="all">All years</option></select></label><label>Type<select id="pub-type"><option value="all">All types</option><option>Journal article</option><option>Conference paper</option><option>Review</option><option>Book chapter</option></select></label></div><div class="result-row"><p id="pub-count" role="status" aria-live="polite"></p><button class="outline" id="export-bib" disabled>Download BibTeX</button></div><div id="publication-list"></div><div class="scope-note"><strong>Collection scope</strong><p>This collection includes papers explicitly confirmed to carry NIT Delhi affiliation. For Dr. Pandey's complete publication record, visit his researcher profiles.</p><div class="profiles" data-profiles></div></div></div></section>'''
contents['people.html']=intro('OUR COMMUNITY','People','Students and researchers associated with ASMD Lab, across undergraduate, postgraduate, doctoral and postdoctoral research.')+'''<section class="section compact"><div class="wrap"><article class="pi-card"><div class="pi-small" aria-hidden="true">RP</div><div><span class="eyebrow">LAB IN-CHARGE</span><h2>Dr. Rahul Pandey</h2><p>Assistant Professor, Department of Applied Sciences (Physics)<br>National Institute of Technology Delhi</p><a href="mailto:rahulpandey@nitdelhi.ac.in">rahulpandey@nitdelhi.ac.in</a></div></article><div class="member-controls"><div class="tabs" role="group" aria-label="Member status"><button data-status="present" aria-pressed="true">Present members</button><button data-status="past" aria-pressed="false">Past members</button></div><label>Research level<select id="member-level"><option value="all">All levels</option><option value="UG">UG</option><option value="PG">PG</option><option value="PhD">PhD</option><option value="Post-Doc">Post-Docs</option></select></label></div><div id="member-list"></div><div class="callout"><h3>Interested in working with us?</h3><p>Tell us about your academic background, research interests and the project or opportunity you wish to discuss.</p><a class="text-link" href="contact.html#join">Research enquiries →</a></div></div></section>'''
contents['news.html']=intro('LATEST UPDATES','News from the lab','Research updates, publications, achievements and announcements.')+'''<section class="section compact"><div class="wrap"><div id="news-list"></div></div></section>'''
contents['events.html']=intro('LEARNING & EXCHANGE','Events','Workshops, seminars, internships and research meetings.')+'''<section class="section compact"><div class="wrap"><div class="tabs" role="group" aria-label="Event dates"><button data-events="all" aria-pressed="true">All events</button><button data-events="upcoming" aria-pressed="false">Upcoming</button><button data-events="past" aria-pressed="false">Past events</button></div><div id="event-list"></div></div></section>'''
contents['gallery.html']=intro('LIFE & WORK AT ASMD','Image gallery','A space for lab photographs, research activities, workshops and student milestones.')+'''<section class="section compact"><div class="wrap"><div class="tabs" role="group" aria-label="Gallery categories"><button data-gallery="all" aria-pressed="true">All</button><button data-gallery="Lab" aria-pressed="false">Lab</button><button data-gallery="Events" aria-pressed="false">Events</button><button data-gallery="People" aria-pressed="false">People</button><button data-gallery="Research" aria-pressed="false">Research</button></div><div id="gallery-list"></div><div class="research-visuals"><p class="eyebrow">OUR RESEARCH IN IMAGES</p><h2>Materials, energy & electronics</h2><p>Conceptual research illustrations used in the lab's visual identity.</p><div class="visual-grid"><figure><div class="visual wafer" role="img" aria-label="Conceptual semiconductor wafer"></div><figcaption>Semiconductor devices</figcaption></figure><figure><div class="visual solar" role="img" aria-label="Conceptual thin-film solar cell"></div><figcaption>Photovoltaics</figcaption></figure><figure><div class="visual atoms" role="img" aria-label="Conceptual atomic crystal lattice"></div><figcaption>Computational materials</figcaption></figure></div></div></div></section><dialog id="lightbox"><button class="close" aria-label="Close image">×</button><img alt=""><p></p></dialog>'''
contents['contact.html']=intro('GET IN TOUCH','Contact & opportunities','Discuss research questions, student projects and collaborations with ASMD Lab.')+'''<section class="section compact"><div class="wrap two-col"><article class="contact-card"><p class="eyebrow">LAB IN-CHARGE</p><h2>Dr. Rahul Pandey</h2><p>Assistant Professor<br>Department of Applied Sciences (Physics)<br>National Institute of Technology Delhi</p><a class="button" href="mailto:rahulpandey@nitdelhi.ac.in">Email the lab ↗</a><p><a href="mailto:rahulpandey@nitdelhi.ac.in">rahulpandey@nitdelhi.ac.in</a></p><div class="profiles" data-profiles></div></article><article class="contact-card"><p class="eyebrow">INSTITUTION</p><h2>NIT Delhi</h2><p>Plot No. FA7, Zone P1, GT Karnal Road<br>Delhi – 110036, India</p><p>Dr. Pandey's institutional office listing:<br>Room 203, UG Physics Lab, 2nd Floor, Mini Campus.</p><p>Contact us before visiting to confirm the meeting location.</p><a class="text-link" href="https://faculty.nitdelhi.ac.in/RahulPandey/profile" target="_blank" rel="noopener noreferrer">Institutional faculty page ↗</a></article></div></section><section class="section pale" id="join"><div class="wrap"><p class="eyebrow">JOIN & COLLABORATE</p><h2>Start a research conversation</h2><div class="opportunities"><article><h3>UG & PG projects</h3><p>For project enquiries, share your programme, research interests and proposed duration.</p></article><article><h3>PhD & postdoctoral research</h3><p>Discuss research fit with the lab. Formal applications follow the applicable institute announcements and procedures.</p><a href="https://nitdelhi.ac.in/" target="_blank" rel="noopener noreferrer">NIT Delhi announcements ↗</a></article><article><h3>Research collaborations</h3><p>We welcome enquiries relating to materials, photovoltaics, semiconductor devices and sensing.</p></article></div><a class="button" href="mailto:rahulpandey@nitdelhi.ac.in?subject=ASMD%20Lab%20research%20enquiry">Send a research enquiry ↗</a></div></section>'''
for filename,body in contents.items():
 title=next((label for url,label in nav if url==filename),'Contact')
 html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="ASMD Lab at NIT Delhi: semiconductor materials, photovoltaic devices, research publications and people. Led by Dr. Rahul Pandey."><meta name="theme-color" content="#11283f"><title>'+title+' | ASMD Lab · NIT Delhi</title><link rel="icon" type="image/png" href="assets/nit-delhi-logo.png"><link rel="stylesheet" href="styles.css"><script defer src="content.js"></script><script defer src="app.js"></script></head><body>'+header(filename)+'<main id="main">'+body+'</main>'+footer()+'</body></html>'
 (root/filename).write_text(html)
print('Generated 8 responsive pages and editable content file.')
