/* Content in this review preview has not been committed to GitHub.
   Add confirmed news entries to news below; examples and LinkedIn fields are in README.md. */
window.LAB_CONTENT = {
  "updated": "2026-10-08",
  "profiles": [
    {
      "name": "Scopus",
      "icon": "scopus",
      "url": "https://www.scopus.com/authid/detail.uri?authorId=56609687400"
    },
    {
      "name": "Web of Science",
      "icon": "wos",
      "url": "https://www.webofscience.com/wos/author/record/IAN-2528-2023"
    },
    {
      "name": "ResearchGate",
      "icon": "rg",
      "url": "https://www.researchgate.net/profile/Rahul-Pandey-3"
    },
    {
      "name": "LinkedIn",
      "icon": "linkedin",
      "url": "https://www.linkedin.com/in/rahul-pandey-%F0%9F%87%AE%F0%9F%87%B3-856a18183/"
    },
    {
      "name": "Google Scholar",
      "icon": "scholar",
      "url": "https://scholar.google.com/citations?hl=en&user=NMz9JVsAAAAJ"
    },
    {
      "name": "ORCID",
      "icon": "orcid",
      "url": "https://orcid.org/0000-0001-7766-3572"
    }
  ],
  "publications": [
    {
      "title": "Impedance spectroscopy reveals electrochemical signatures of charge transfer and carrier relaxation in compositionally graded Cd(Te1−xSex) thin-film solar cells",
      "authors": "Singh S.; Gahlawat D.; Kaur J.; Basu R.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Singh, Sarthak and Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Physics and Chemistry of Solids",
      "year": 2027,
      "doi": "10.1016/j.jpcs.2026.114093",
      "type": "Journal article",
      "volume": "220",
      "issue": "",
      "articleNumber": "114093",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 11036, India",
      "url": "https://www.scopus.com/pages/publications/105049176993?origin=resultslist",
      "tags": [
        "Cd(Se,Te) solar cells",
        "Compositional grading",
        "Drift–diffusion simulation",
        "Electrochemical impedance spectroscopy",
        "Recombination dynamics"
      ],
      "sourceRow": 36
    },
    {
      "title": "26.1 % efficient lead-free perovskite tandem solar cell using DJ and Cs2CrI6: A numerical study",
      "authors": "Kaur N.; Madan J.; Pandey R.",
      "bibtexAuthors": "Kaur, Navdeep and Madan, Jaya and Pandey, Rahul",
      "journal": "Micro and Nanostructures",
      "year": 2026,
      "doi": "10.1016/j.micrna.2025.208381",
      "type": "Journal article",
      "volume": "209",
      "issue": "",
      "articleNumber": "208381",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105020262852?origin=resultslist",
      "tags": [
        "Double perovskite",
        "Lead free perovskite",
        "SCAPS -1D",
        "Solar cell",
        "Tandem solar cell"
      ],
      "sourceRow": 76
    },
    {
      "title": "A unified statistical perspective on bandgap engineering across the Ba(Hf1−xZrx)S3chalcogenide perovskite system",
      "authors": "Gahlawat D.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "Materials Today Physics",
      "year": 2026,
      "doi": "10.1016/j.mtphys.2025.101959",
      "type": "Journal article",
      "volume": "60",
      "issue": "",
      "articleNumber": "101959",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105024850454?origin=resultslist",
      "tags": [
        "Bandgap engineering",
        "Chalcogenide perovskites",
        "Compositional grading",
        "Interpretable machine learning",
        "SCAPS-1D simulation"
      ],
      "sourceRow": 293
    },
    {
      "title": "Advanced Modeling of CdTe BSF-Based Multi-Layer Antimony Chalcogenide (Sb2Se3/Sb2S3) Double Absorber Solar Cells: Optimization of Key Physical Parameters Using SCAPS-1D",
      "authors": "Gupta G.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gupta, Gauri and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Advanced Theory and Simulations",
      "year": 2026,
      "doi": "10.1002/adts.70529",
      "type": "Journal article",
      "volume": "9",
      "issue": "8",
      "articleNumber": "e70529",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology (NIT), Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105048076653?origin=resultslist",
      "tags": [
        "antimony chalcogenides",
        "bandgap engineering",
        "non-toxic thin-film solar cells",
        "Sb<sub>2</sub>S<sub>3</sub>/Sb<sub>2</sub>Se<sub>3</sub> double absorber",
        "SCAPS-1D simulation"
      ],
      "sourceRow": 216
    },
    {
      "title": "Advanced Numerical Insights into Bandgap-Tuned Cs₂Ti(Cl₁₋ₓBrₓ)6 for High-Efficiency Solar Applications",
      "authors": "Pamwani V.; Gupta S.; Nikita; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Pamwani, Vipul and Gupta, Syamantak and Nikita and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Materials Science and Engineering: B",
      "year": 2026,
      "doi": "10.1016/j.mseb.2025.118897",
      "type": "Journal article",
      "volume": "324",
      "issue": "",
      "articleNumber": "118897",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105020672646?origin=resultslist",
      "tags": [
        "Band gap tuning",
        "Double perovskite",
        "PCE",
        "PV devices",
        "Solar cell"
      ],
      "sourceRow": 2
    },
    {
      "title": "Advanced Tuning of Optoelectronic and Structural Parameters in Cs2AgBiI6-Based Lead-Free Perovskite Solar Cells: Toward 28.95% Efficiency",
      "authors": "Bhattarai S.; Roy P.; Shrivastav N.; Dakua P.K.; Pandey R.; Madan J.",
      "bibtexAuthors": "Bhattarai, Sagar and Roy, Priyanka and Shrivastav, Nikhil and Dakua, Pratap Kumar and Pandey, Rahul and Madan, Jaya",
      "journal": "ChemistrySelect",
      "year": 2026,
      "doi": "10.1002/slct.73496",
      "type": "Journal article",
      "volume": "11",
      "issue": "19",
      "articleNumber": "e73496",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105039495036?origin=resultslist",
      "tags": [
        "methyl ammonium (MA)",
        "perovskite solar cells (PSCs)",
        "power conversion efficiency (PCE)",
        "SCAPS-1D software"
      ],
      "sourceRow": 104
    },
    {
      "title": "Comparative Performance Optimization of MASnX3(X = I, Br)/CsSnI3 Double-Absorber Perovskite Solar Cells: A SCAPS Study Towards Eco-Friendly High-Efficiency Devices",
      "authors": "Khatua M.; Punia D.; Sharma A.K.; Malhotra J.; Basu R.; Madan J.; Pandey R.",
      "bibtexAuthors": "Khatua, Monalisa and Punia, Divya and Sharma, Ajay Kumar and Malhotra, Jyoteesh and Basu, Rikmantra and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Electronic Materials",
      "year": 2026,
      "doi": "10.1007/s11664-026-13001-x",
      "type": "Journal article",
      "volume": "55",
      "issue": "9",
      "articleNumber": "",
      "pages": "7578–7593",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105043825316?origin=resultslist",
      "tags": [
        "acceptor doping density variation",
        "double-absorber perovskite solar cells (DAPSCs)",
        "perovskite solar cells (PSCs)",
        "photovoltaic (PV) parameter variation",
        "thickness variation",
        "Tin (Sn)-based perovskites",
        "total defect density variation"
      ],
      "sourceRow": 227
    },
    {
      "title": "Compositional grading strategies in Ba(Hf1−xZrx)S3 chalcogenide perovskites: Mapping the device physics of bandgap-engineered architectures",
      "authors": "Gahlawat D.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "Micro and Nanostructures",
      "year": 2026,
      "doi": "10.1016/j.micrna.2026.208760",
      "type": "Journal article",
      "volume": "217",
      "issue": "",
      "articleNumber": "208760",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105040367117?origin=resultslist",
      "tags": [
        "Capacitance voltage characteristics",
        "Dielectric loss",
        "Electrochemical impedance spectroscopy",
        "Mott–Schottky",
        "SCAPS-1D simulation"
      ],
      "sourceRow": 253
    },
    {
      "title": "Computational analysis of inorganic Cs2AgMBr6-based double perovskite solar cells for underwater applications via SCAPS-1D",
      "authors": "Rajak A.; Basu R.; Kundara R.; Madan J.; Pandey R.",
      "bibtexAuthors": "Rajak, Ankush and Basu, Rikmantra and Kundara, Rahul and Madan, Jaya and Pandey, Rahul",
      "journal": "Inorganic Chemistry Communications",
      "year": 2026,
      "doi": "10.1016/j.inoche.2026.116382",
      "type": "Journal article",
      "volume": "187",
      "issue": "",
      "articleNumber": "116382",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology (NIT), Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105034319010?origin=resultslist",
      "tags": [
        "Cs<sub>2</sub>AgGaBr<sub>6</sub>",
        "Cs<sub>2</sub>AgInBr<sub>6</sub>",
        "ETL and HTL",
        "SCAPS-1D",
        "Underwater"
      ],
      "sourceRow": 135
    },
    {
      "title": "Dual-absorber Cs2TiF6/Dion–Jacobson perovskite solar cells achieving 24.5 % efficiency for underwater applications: A SCAPS-1D study",
      "authors": "Singh K.; Basu R.; Sharma A.K.; Kundara R.; Madan J.; Pandey R.",
      "bibtexAuthors": "Singh, Keshav and Basu, Rikmantra and Sharma, Ajay Kumar and Kundara, Rahul and Madan, Jaya and Pandey, Rahul",
      "journal": "Solid State Communications",
      "year": 2026,
      "doi": "10.1016/j.ssc.2026.116513",
      "type": "Journal article",
      "volume": "416",
      "issue": "",
      "articleNumber": "116513",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology (NIT), Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105044425401?origin=resultslist",
      "tags": [
        "Cs<sub>2</sub>TiF<sub>6</sub>",
        "Dion-Jacobson",
        "SCAPS-1D",
        "Underwater"
      ],
      "sourceRow": 141
    },
    {
      "title": "Exploring the Potential of CsGeI3 Photovoltaics: Simulation Based Investigation for Optimal Device Configuration and Efficiency",
      "authors": "Roopam; Malhotra J.; Madan J.; Pandey R.",
      "bibtexAuthors": "Roopam and Malhotra, Jyoteesh and Madan, Jaya and Pandey, Rahul",
      "journal": "Advanced Theory and Simulations",
      "year": 2026,
      "doi": "10.1002/adts.70491",
      "type": "Journal article",
      "volume": "9",
      "issue": "8",
      "articleNumber": "e70491",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105046587558?origin=resultslist",
      "tags": [
        "(i-CsGeI<sub>3</sub>)",
        "intrinsic absorber layer",
        "PSC",
        "SCAPS-1D",
        "solar cell"
      ],
      "sourceRow": 306
    },
    {
      "title": "First principles guided multiphysics simulation of bandgap-graded SiGe solar cells with dielectric nanoparticle light trapping",
      "authors": "Nikita; Kaur J.; Verma P.; Sharma A.K.; Madan J.; Pandey R.; Basu R.",
      "bibtexAuthors": "Nikita and Kaur, Jaspinder and Verma, Preeti and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul and Basu, Rikmantra",
      "journal": "Solar Energy",
      "year": 2026,
      "doi": "10.1016/j.solener.2026.115045",
      "type": "Journal article",
      "volume": "318",
      "issue": "",
      "articleNumber": "115045",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105049615139?origin=resultslist",
      "tags": [
        "DFT",
        "Grading",
        "Group IV alloys",
        "Nanoparticle",
        "Plasmonic",
        "SiGe",
        "Solar cells"
      ],
      "sourceRow": 292
    },
    {
      "title": "Harnessing Machine Learning to Predict and Optimize the Performance of MASnI3/FASnI3 Double-Absorber Lead-Free Perovskite Solar Cells",
      "authors": "Panda P.; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Panda, Pratyush and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Advanced Theory and Simulations",
      "year": 2026,
      "doi": "10.1002/adts.70512",
      "type": "Journal article",
      "volume": "9",
      "issue": "8",
      "articleNumber": "e70512",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105047235856?origin=resultslist",
      "tags": [
        "carboost",
        "double absorber efficiency optimisation",
        "FASnI<sub>3</sub>",
        "machine learning",
        "MASnI<sub>3</sub>",
        "perovskite solar cell",
        "random forest",
        "supported vector regression",
        "XGBoost"
      ],
      "sourceRow": 289
    },
    {
      "title": "Influence of surface albedo on the efficiency of KGeCl3-based bifacial solar cells",
      "authors": "Shrivastav N.; Madan J.; Alla M.; Pandey R.",
      "bibtexAuthors": "Shrivastav, Nikhil and Madan, Jaya and Alla, Mohamed and Pandey, Rahul",
      "journal": "Materials Letters",
      "year": 2026,
      "doi": "10.1016/j.matlet.2025.139878",
      "type": "Journal article",
      "volume": "406",
      "issue": "",
      "articleNumber": "139878",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Karnal Road, GT, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105023668604?origin=resultslist",
      "tags": [
        "Albedo effect",
        "Bifacial solar cells",
        "KGeCl<sub>3</sub>",
        "PCE and Nyquist"
      ],
      "sourceRow": 105
    },
    {
      "title": "Investigating the optoelectronic performance of PeDAMA5Pb6I19 Dion–Jacobson perovskite solar cells through SCAPS-1D numerical simulation",
      "authors": "Saxena H.; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Saxena, Harshit and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Physics and Chemistry of Solids",
      "year": 2026,
      "doi": "10.1016/j.jpcs.2025.113103",
      "type": "Journal article",
      "volume": "208",
      "issue": "",
      "articleNumber": "113103",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105013574111?origin=resultslist",
      "tags": [
        "2D perovskite",
        "Dion-Jacobson perovskite",
        "Efficiency",
        "Perovskite solar cells",
        "Photovoltaics",
        "SCAPS-1D"
      ],
      "sourceRow": 130
    },
    {
      "title": "Layered transition metal dichalcogenides in photovoltaics: Structure-interface correlation and device simulation insights",
      "authors": "Gahlawat D.; Baranwal K.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gahlawat, Devansh and Baranwal, Kushagra and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "Electrochimica Acta",
      "year": 2026,
      "doi": "10.1016/j.electacta.2026.148148",
      "type": "Journal article",
      "volume": "551",
      "issue": "",
      "articleNumber": "148148",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105027311073?origin=resultslist",
      "tags": [
        "EIS analysis",
        "Interface defects",
        "MoX<sub>2</sub> solar cells",
        "Photovoltaic performance",
        "SCAPS-1D simulation"
      ],
      "sourceRow": 252
    },
    {
      "title": "Mitigating sub-bandgap transmission losses through Cu alloying and gradient engineering in CdTe solar cells: A numerical simulation study",
      "authors": "Singh S.; Gahlawat D.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Singh, Sarthak and Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "Next Materials",
      "year": 2026,
      "doi": "10.1016/j.nxmate.2026.102428",
      "type": "Journal article",
      "volume": "12",
      "issue": "",
      "articleNumber": "102428",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105041247519?origin=resultslist",
      "tags": [
        "Bandgap engineering",
        "CdTe",
        "Compositional grading",
        "SCAPS-1D",
        "Thin-film photovoltaics"
      ],
      "sourceRow": 9
    },
    {
      "title": "Modeling and Optimization of Novel Cs2AlBiCl6-Based Double Perovskite Solar Cells for Underwater Applications: A Comprehensive Study",
      "authors": "Kundara R.; Basu R.; Madan J.; Pandey R.",
      "bibtexAuthors": "Kundara, Rahul and Basu, Rikmantra and Madan, Jaya and Pandey, Rahul",
      "journal": "IEEE Transactions on Electron Devices",
      "year": 2026,
      "doi": "10.1109/TED.2026.3691694",
      "type": "Journal article",
      "volume": "73",
      "issue": "7",
      "articleNumber": "",
      "pages": "4280–4286",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., National Institute of Technology Delhi, Department of Applied Sciences (Physics), Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105039327176?origin=resultslist",
      "tags": [
        "Cs<sub>2</sub>AlBiCl<sub>6</sub>",
        "current-density characteristics (J-V)",
        "double perovskite material",
        "perovskite solar cell (PSC)",
        "photovoltaics (PVs)",
        "quantum efficiency (QE)",
        "solar cell capacitance simulator (SCAPS)"
      ],
      "sourceRow": 139
    },
    {
      "title": "Multi architecture simulation and predictive modelling of high efficiency lead free perovskite solar cells",
      "authors": "Yadav V.; Shrivastav N.; Pandey R.; Madan J.",
      "bibtexAuthors": "Yadav, Vishal and Shrivastav, Nikhil and Pandey, Rahul and Madan, Jaya",
      "journal": "Solar Energy",
      "year": 2026,
      "doi": "10.1016/j.solener.2026.114650",
      "type": "Journal article",
      "volume": "313",
      "issue": "",
      "articleNumber": "114650",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105037399822?origin=resultslist",
      "tags": [
        "Efficiency",
        "Machine learning",
        "Perovskite solar cell",
        "Simulation"
      ],
      "sourceRow": 310
    },
    {
      "title": "Multiphysics simulation of carrier transport and thermal behavior in n+Si/Si1-xGex/p-Si/p+Si heterojunction solar cells",
      "authors": "Nikita; Kaur J.; Verma P.; Sharma A.K.; Madan J.; Pandey R.; Basu R.",
      "bibtexAuthors": "Nikita and Kaur, Jaspinder and Verma, Preeti and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul and Basu, Rikmantra",
      "journal": "Physica B: Condensed Matter",
      "year": 2026,
      "doi": "10.1016/j.physb.2026.418943",
      "type": "Journal article",
      "volume": "739",
      "issue": "",
      "articleNumber": "418943",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105042104856?origin=resultslist",
      "tags": [
        "Grading",
        "Group IV",
        "Si",
        "Si<sub>(1-x)</sub>Ge<sub>(x)</sub>",
        "Solar cells"
      ],
      "sourceRow": 273
    },
    {
      "title": "Novel Combination of Inorganic Dual-Absorber Perovskite Solar Cell (Cs2TiI6/Cs2CuBiCl6): SCAPS-1D Optimization and Underwater Analysis",
      "authors": "Sahu K.; Basu R.; Kundara R.; Madan J.; Pandey R.",
      "bibtexAuthors": "Sahu, Karan and Basu, Rikmantra and Kundara, Rahul and Madan, Jaya and Pandey, Rahul",
      "journal": "Physica Status Solidi (A) Applications and Materials Science",
      "year": 2026,
      "doi": "10.1002/pssa.70404",
      "type": "Journal article",
      "volume": "223",
      "issue": "11",
      "articleNumber": "e70404",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105041294105?origin=resultslist",
      "tags": [
        "Cs<sub>2</sub>CuBiCl<sub>6</sub>",
        "Cs<sub>2</sub>TiI<sub>6</sub>",
        "ETL and HTL",
        "SCAPS-1D",
        "underwater"
      ],
      "sourceRow": 178
    },
    {
      "title": "Numerical optimization and synergistic engineering of 2D/3D perovskite absorbers for enhanced photovoltaic performance in high-efficiency solar cells",
      "authors": "Panda P.; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Panda, Pratyush and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Physics and Chemistry of Solids",
      "year": 2026,
      "doi": "10.1016/j.jpcs.2025.113297",
      "type": "Journal article",
      "volume": "209",
      "issue": "",
      "articleNumber": "113297",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105020262023?origin=resultslist",
      "tags": [
        "2D/3D bilayer architecture",
        "Dion–jacobson (DJ) perovskite",
        "Impedance spectroscopy",
        "Perovskite solar cells (PSCs)",
        "Photovoltaic optimization",
        "SCAPS-1D simulation"
      ],
      "sourceRow": 68
    },
    {
      "title": "Photovoltaic Performance of Lead-Free Na2GeBr6 Perovskite Investigated via Density Functional Theory and SCAPS-1D Modeling",
      "authors": "Dixit A.; Abraham J.A.; Mishra A.K.; Madan J.; Pandey R.; Shrivastav N.; Kumar Y.A.; Sharma R.",
      "bibtexAuthors": "Dixit, Aparna and Abraham, Jisha Annie and Mishra, Abhishek Kumar and Madan, Jaya and Pandey, Rahul and Shrivastav, Nikhil and Kumar, Yedluri Anil and Sharma, Ramesh",
      "journal": "Energy Technology",
      "year": 2026,
      "doi": "10.1002/ente.70483",
      "type": "Journal article",
      "volume": "14",
      "issue": "4",
      "articleNumber": "e70483",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105036039521?origin=resultslist",
      "tags": [
        "density functional theory (DFT)",
        "lead-free perovskite",
        "SCAPS-1D",
        "solar cell"
      ],
      "sourceRow": 262
    },
    {
      "title": "Reliability Analysis of IGZO Thin-Film Transistor for Wearable Biosensing Applications",
      "authors": "Thakur A.; Sharma S.; Madan J.; Pandey R.",
      "bibtexAuthors": "Thakur, Anchal and Sharma, Samriti and Madan, Jaya and Pandey, Rahul",
      "journal": "IEEE Transactions on Device and Materials Reliability",
      "year": 2026,
      "doi": "10.1109/TDMR.2026.3684091",
      "type": "Journal article",
      "volume": "26",
      "issue": "2",
      "articleNumber": "",
      "pages": "637–644",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., National Institute of Technology Delhi, Department of Applied Sciences (Physics), Narela, New Delhi, 110040, India",
      "url": "https://www.scopus.com/pages/publications/105036642174?origin=resultslist",
      "tags": [
        "band bending",
        "compressive and tensile strain",
        "indium gallium zinc oxide (IGZO)",
        "Thin film transistor (TFTs)",
        "wearable biosensors"
      ],
      "sourceRow": 111
    },
    {
      "title": "SiGeSn alloy solar cells: Noise, recombination, and performance insights",
      "authors": "Nikita; Kaur J.; Verma P.; Sharma A.K.; Madan J.; Pandey R.; Basu R.",
      "bibtexAuthors": "Nikita and Kaur, Jaspinder and Verma, Preeti and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul and Basu, Rikmantra",
      "journal": "Micro and Nanostructures",
      "year": 2026,
      "doi": "10.1016/j.micrna.2026.208568",
      "type": "Journal article",
      "volume": "212",
      "issue": "",
      "articleNumber": "208568",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105027728448?origin=resultslist",
      "tags": [
        "Auger recombination",
        "Group 4,Si<sub>1-x-y</sub>Ge<sub>y</sub>Sn<sub>x</sub>",
        "Radiative recombination",
        "Series resistance",
        "Shunt resistance"
      ],
      "sourceRow": 232
    },
    {
      "title": "Simulation Study of a Gradient-Engineered 2D DJ–3D Hybrid Perovskite Solar Cell Architecture",
      "authors": "Panda P.; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Panda, Pratyush and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Physica Status Solidi (A) Applications and Materials Science",
      "year": 2026,
      "doi": "10.1002/pssa.70428",
      "type": "Journal article",
      "volume": "223",
      "issue": "14",
      "articleNumber": "e70428",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105044015691?origin=resultslist",
      "tags": [
        "Ba(Zr, Ti)S<sub>3</sub> absorber",
        "bandgap grading",
        "bowing factor variation",
        "double absorber architecture",
        "graded perovskite solar cell",
        "PeDA-based Dion–Jacobson (DJ) perovskite",
        "recombination-generation analysis"
      ],
      "sourceRow": 182
    },
    {
      "title": "Sinusoidal graded CsSnI3-xBrx absorbers with composition profiling for next-generation high-efficiency solar cells",
      "authors": "Kaur N.; Madan J.; Pandey R.",
      "bibtexAuthors": "Kaur, Navdeep and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Physics and Chemistry of Solids",
      "year": 2026,
      "doi": "10.1016/j.jpcs.2026.113821",
      "type": "Journal article",
      "volume": "217",
      "issue": "",
      "articleNumber": "113821",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105041057238?origin=resultslist",
      "tags": [
        "All-inorganic Sn-Based perovskite",
        "Photovoltaic",
        "Sinusoidal graded absorber layer",
        "Solar cells"
      ],
      "sourceRow": 220
    },
    {
      "title": "Synergetic integration of Dion-Jacobson tin-based perovskite for enhanced charge transport and stability: Attaining 31.98 % efficiency",
      "authors": "Katiyar P.; Singh Y.K.; Dwivedi D.K.; Lohia P.; Pandey R.; Yadav R.K.; Verma A.A.; Kulshrestha U.",
      "bibtexAuthors": "Katiyar, Pulkit and Singh, Yashwant Kumar and Dwivedi, D.K. and Lohia, Pooja and Pandey, Rahul and Yadav, R.K. and Verma, Akash Anand and Kulshrestha, Upendra",
      "journal": "Electrochimica Acta",
      "year": 2026,
      "doi": "10.1016/j.electacta.2025.147854",
      "type": "Journal article",
      "volume": "547",
      "issue": "",
      "articleNumber": "147854",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics) National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105023186122?origin=resultslist",
      "tags": [
        "2D-3D perovskite",
        "Affordable and clean energy",
        "DJ phase",
        "SCAPS 1D",
        "Solar cell"
      ],
      "sourceRow": 152
    },
    {
      "title": "Tackling interface defects and optical losses in perovskite solar cells using 2D perovskites and MgF2 texturing to achieve 27% efficiency",
      "authors": "Yadav V.; Shrivastav N.; Pandey R.; Madan J.",
      "bibtexAuthors": "Yadav, Vishal and Shrivastav, Nikhil and Pandey, Rahul and Madan, Jaya",
      "journal": "Journal of Optics (India)",
      "year": 2026,
      "doi": "10.1007/s12596-026-03166-3",
      "type": "Journal article",
      "volume": "",
      "issue": "",
      "articleNumber": "",
      "pages": "",
      "publicationStage": "Article in press",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology (NIT), Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105040581247?origin=resultslist",
      "tags": [
        "2D Perovskites",
        "MgF<sub>2</sub>",
        "Optical Loss Reduction",
        "Perovskite Solar Cells",
        "Texturing"
      ],
      "sourceRow": 231
    },
    {
      "title": "Advanced computational modeling and performance optimization of 3D/3D bilayer perovskite heterojunction in monolithic tandem photovoltaic device",
      "authors": "Singh B.; Kumar S.; Kaur J.; Basu R.; Sharma A.K.; Pandey R.; Madan J.",
      "bibtexAuthors": "Singh, Bhupender and Kumar, Surender and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Pandey, Rahul and Madan, Jaya",
      "journal": "Micro and Nanostructures",
      "year": 2025,
      "doi": "10.1016/j.micrna.2025.208319",
      "type": "Journal article",
      "volume": "207",
      "issue": "",
      "articleNumber": "208319",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105014817544?origin=resultslist",
      "tags": [
        "FA<sub>0.7</sub>MA<sub>0.3</sub>Pb<sub>0.5</sub>Sn<sub>0.5</sub>I<sub>3</sub>, FA<sub>0.7</sub>Cs<sub>0.3</sub>Pb(I<sub>0.85</sub>Br<sub>0.14</sub>)<sub>3</sub>, SCAPS-1D",
        "FA<sub>0.8</sub>Cs<sub>0.2</sub>Pb(I<sub>0.6</sub>Br<sub>0.4</sub>)<sub>3</sub>",
        "Tandem solar cell"
      ],
      "sourceRow": 55
    },
    {
      "title": "Application of Machine Learning for Performance Analysis and Composition Tuning in Mixed Halide Cs2Ti(Cl1−xBrx)6 Solar Devices",
      "authors": "Pamwani V.; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Pamwani, Vipul and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Electronic Materials",
      "year": 2025,
      "doi": "10.1007/s11664-025-12463-9",
      "type": "Journal article",
      "volume": "54",
      "issue": "12",
      "articleNumber": "",
      "pages": "11471–11482",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105019983022?origin=resultslist",
      "tags": [
        "ML",
        "Pearson plot",
        "random forest",
        "SHAP plot",
        "solar cell",
        "SVR",
        "XGBoost"
      ],
      "sourceRow": 7
    },
    {
      "title": "Augmenting the filtered spectrum and current matching analysis of synergistic Dion-Jacobson 2D-3D Perovskite-CIGS tandem solar Cell: Achieving 32.56% efficiency",
      "authors": "Pathak G.; Singh Y.K.; Dwivedi D.K.; Lohia P.; Pandey R.; Kulshrestha U.; Kumar M.",
      "bibtexAuthors": "Pathak, Gauri and Singh, Yashwant Kumar and Dwivedi, D.K. and Lohia, Pooja and Pandey, Rahul and Kulshrestha, Upendra and Kumar, Manish",
      "journal": "Materials Science and Engineering: B",
      "year": 2025,
      "doi": "10.1016/j.mseb.2025.118599",
      "type": "Journal article",
      "volume": "322",
      "issue": "",
      "articleNumber": "118599",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105010211881?origin=resultslist",
      "tags": [
        "Affordable & Clean Energy",
        "Current matching",
        "Filtered spectrum",
        "SCAPS-1D",
        "Tandem solar cell"
      ],
      "sourceRow": 41
    },
    {
      "title": "Bandgap Engineering and Impedance Spectroscopy Analysis of Linearly Graded Group IV Material-based Alloys for Photovoltaic Applications",
      "authors": "Gahlawat D.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "Silicon",
      "year": 2025,
      "doi": "10.1007/s12633-025-03442-0",
      "type": "Journal article",
      "volume": "17",
      "issue": "15-16",
      "articleNumber": "",
      "pages": "3667–3689",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology, New Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105013552026?origin=resultslist",
      "tags": [
        "Equivalent Circuit Models (ECMs)",
        "Impedance Spectroscopy",
        "Johnson-Nyquist Noise",
        "SCAPS-1D",
        "SiGeSn",
        "Vegard’s Law"
      ],
      "sourceRow": 251
    },
    {
      "title": "Current matched all perovskite tandem solar cells with low lead perovskites achieving 31.9% efficiency and enhanced stability",
      "authors": "Kaur N.; Madan J.; Perumal A.; Pandey R.",
      "bibtexAuthors": "Kaur, Navdeep and Madan, Jaya and Perumal, Asaithambi and Pandey, Rahul",
      "journal": "Scientific Reports",
      "year": 2025,
      "doi": "10.1038/s41598-025-99575-8",
      "type": "Journal article",
      "volume": "15",
      "issue": "1",
      "articleNumber": "29724",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, India",
      "url": "https://www.scopus.com/pages/publications/105013190071?origin=resultslist",
      "tags": [
        "Double perovskite",
        "Low - lead all inorganic perovskite",
        "SCAPS−1D",
        "Tandem solar cell"
      ],
      "sourceRow": 248
    },
    {
      "title": "Efficiency enhancement in perovskite solar cells through optimized MgF2 textured surface engineering: Light-management optimization",
      "authors": "Yadav V.; Pandey R.; Madan J.",
      "bibtexAuthors": "Yadav, Vishal and Pandey, Rahul and Madan, Jaya",
      "journal": "Micro and Nanostructures",
      "year": 2025,
      "doi": "10.1016/j.micrna.2025.208283",
      "type": "Journal article",
      "volume": "207",
      "issue": "",
      "articleNumber": "208283",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105012309841?origin=resultslist",
      "tags": [
        "Efficiency",
        "Light management",
        "Perovskite solar cells",
        "Photovoltaic",
        "Surface engineering",
        "Texturing"
      ],
      "sourceRow": 297
    },
    {
      "title": "Exploring elpasolite double perovskites Ba2XIO6 (X = Au and Ag) for non-toxic and stable photovoltaics: numerical optimization and device analysis",
      "authors": "Gahlawat D.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "New Journal of Chemistry",
      "year": 2025,
      "doi": "10.1039/d5nj01075f",
      "type": "Journal article",
      "volume": "49",
      "issue": "27",
      "articleNumber": "",
      "pages": "11930–11947",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105008978214?origin=resultslist",
      "tags": [],
      "sourceRow": 269
    },
    {
      "title": "Exploring photovoltaic device-level study of K2XAuCl6 (X = Al, Ga) double perovskites using DFT and SCAPS-1D approach",
      "authors": "Thakur D.; Dixit A.; Abraham J.A.; Mishra S.; Mishra A.K.; Madan J.; Pandey R.; Shrivastav N.; Sharma R.",
      "bibtexAuthors": "Thakur, Deepa and Dixit, Aparna and Abraham, Jisha Annie and Mishra, Soni and Mishra, Abhishek K. and Madan, Jaya and Pandey, Rahul and Shrivastav, Nikhil and Sharma, Ramesh",
      "journal": "Journal of Computational Electronics",
      "year": 2025,
      "doi": "10.1007/s10825-025-02435-x",
      "type": "Journal article",
      "volume": "24",
      "issue": "6",
      "articleNumber": "204",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105018860103?origin=resultslist",
      "tags": [
        "Absorption coefficient",
        "DFT",
        "Figure of merit",
        "Optoelectronic properties",
        "SCAPS-1D"
      ],
      "sourceRow": 32
    },
    {
      "title": "Exploring photovoltaic potential of group IV ternary Si1-x-yGeySnx alloys in solar cells: An in-depth numerical Analysis",
      "authors": "Nikita; Kaur J.; Verma P.; Sharma A.K.; Madan J.; Pandey R.; Basu R.",
      "bibtexAuthors": "Nikita and Kaur, Jaspinder and Verma, Preeti and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul and Basu, Rikmantra",
      "journal": "Journal of Physics and Chemistry of Solids",
      "year": 2025,
      "doi": "10.1016/j.jpcs.2025.112936",
      "type": "Journal article",
      "volume": "207",
      "issue": "",
      "articleNumber": "112936",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105009000063?origin=resultslist",
      "tags": [
        "Composition",
        "Cu<sub>2</sub>O",
        "Group IV",
        "PCE",
        "Si<sub>1-x-y</sub>Ge<sub>y</sub>Sn<sub>x</sub>",
        "Solar cell",
        "Ternary alloy",
        "WS<sub>2</sub>"
      ],
      "sourceRow": 256
    },
    {
      "title": "Molecular additive-modified rGO/TiO2 photoelectrodes for efficient mesoporous perovskite solar cells",
      "authors": "Mohammed M.K.A.; Ahmed D.S.; Alnayli R.S.; Kanjariya P.; Ballal S.; Rahman M.F.; Al-Mousoi A.K.; Pandey R.; Akman E.",
      "bibtexAuthors": "Mohammed, Mustafa K.A. and Ahmed, Duha S. and Alnayli, Raad Sh. and Kanjariya, Prakash and Ballal, Suhas and Rahman, Md. Ferdous and Al-Mousoi, Ali K. and Pandey, Rahul and Akman, Erdi",
      "journal": "Chemical Physics Letters",
      "year": 2025,
      "doi": "10.1016/j.cplett.2025.142335",
      "type": "Journal article",
      "volume": "877",
      "issue": "",
      "articleNumber": "142335",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105012824442?origin=resultslist",
      "tags": [
        "Electron transport layer",
        "Graphene",
        "Molecular additive",
        "Perovskite",
        "rGO"
      ],
      "sourceRow": 236
    },
    {
      "title": "Numerical insights into the electronic, spectral and impedance characterization of bandgap-engineered Ba(Zr,Ti)S3 photovoltaic structures",
      "authors": "Gahlawat D.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Optics (India)",
      "year": 2025,
      "doi": "10.1007/s12596-025-02754-z",
      "type": "Journal article",
      "volume": "",
      "issue": "",
      "articleNumber": "",
      "pages": "",
      "publicationStage": "Article in press",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105006416971?origin=resultslist",
      "tags": [
        "Impedance spectroscopy",
        "Optoelectronics",
        "Perovskite",
        "SCAPS-1D",
        "Spectral response"
      ],
      "sourceRow": 201
    },
    {
      "title": "Numerical optimization and comparative analysis of bandgap-engineered BaZrS3 chalcogenide perovskite solar cells with site-specific alloying",
      "authors": "Kumar S.; Gahlawat D.; Kaur J.; Madan J.; Pandey R.; Basu R.",
      "bibtexAuthors": "Kumar, Surender and Gahlawat, Devansh and Kaur, Jaspinder and Madan, Jaya and Pandey, Rahul and Basu, Rikmantra",
      "journal": "Physica B: Condensed Matter",
      "year": 2025,
      "doi": "10.1016/j.physb.2025.417351",
      "type": "Journal article",
      "volume": "712",
      "issue": "",
      "articleNumber": "417351",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105004265649?origin=resultslist",
      "tags": [
        "Alloying",
        "Bandgap engineering",
        "Efficiency",
        "Photovoltaics",
        "SCAPS-1D"
      ],
      "sourceRow": 228
    },
    {
      "title": "Optimization of double absorber antimony chalcogenide-based solar cells: A comprehensive parametric optimization to achieve 28.4 % conversion efficiency",
      "authors": "Saxena H.; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Saxena, Harshit and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Micro and Nanostructures",
      "year": 2025,
      "doi": "10.1016/j.micrna.2025.208215",
      "type": "Journal article",
      "volume": "206",
      "issue": "",
      "articleNumber": "208215",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105006672874?origin=resultslist",
      "tags": [
        "BSF",
        "Chalcogenide",
        "Double absorber",
        "Sb<sub>2</sub>S<sub>3</sub>",
        "Sb<sub>2</sub>Se<sub>3</sub>",
        "WS<sub>2</sub>",
        "WSe<sub>2</sub>"
      ],
      "sourceRow": 5
    },
    {
      "title": "Optimizing the Filtered Spectrum and Various Transport Layers of Synergistic Dion–Jacobson 2D–3D Perovskite Tandem Solar Cell: Achieving 32.11% Efficiency",
      "authors": "Pathak G.; Dwivedi D.K.; Lohia P.; Singh Y.K.; Pandey R.; Madan J.; Verma A.A.; Kumar M.",
      "bibtexAuthors": "Pathak, Gauri and Dwivedi, D.K. and Lohia, Pooja and Singh, Yashwant Kumar and Pandey, Rahul and Madan, Jaya and Verma, Akash Anand and Kumar, Manish",
      "journal": "Journal of Inorganic and Organometallic Polymers and Materials",
      "year": 2025,
      "doi": "10.1007/s10904-025-03863-9",
      "type": "Journal article",
      "volume": "35",
      "issue": "11",
      "articleNumber": "",
      "pages": "9356–9370",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, GT Karnal Road, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105006708414?origin=resultslist",
      "tags": [
        "Dion–Jacobson",
        "Filtered spectrum",
        "Perovskite",
        "Solar cell",
        "Tandem"
      ],
      "sourceRow": 206
    },
    {
      "title": "Semi-transparent perovskite solar cells with stacked absorber layer: Balancing power conversion efficiency and visible transmittance",
      "authors": "Kaur N.; Madan J.; Pandey R.",
      "bibtexAuthors": "Kaur, Navdeep and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Physics and Chemistry of Solids",
      "year": 2025,
      "doi": "10.1016/j.jpcs.2025.112868",
      "type": "Journal article",
      "volume": "207",
      "issue": "",
      "articleNumber": "112868",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105006748531?origin=resultslist",
      "tags": [
        "All-inorganic",
        "Perovskite",
        "Solar cell",
        "Stacked absorber layer",
        "Transmittance"
      ],
      "sourceRow": 156
    },
    {
      "title": "Synergistic combination of DJ 2D-3D Layers: Achieving 30.75 % perovskite solar cell efficiency",
      "authors": "Katiyar P.; Dwivedi D.K.; Lohia P.; Pandey R.; Madan J.; Verma A.A.; Mahmoud M.H.H.; Hossain M.K.",
      "bibtexAuthors": "Katiyar, Pulkit and Dwivedi, D.K. and Lohia, Pooja and Pandey, Rahul and Madan, Jaya and Verma, Akash Anand and Mahmoud, Mohamed H.H. and Hossain, M. Khalid",
      "journal": "Journal of Physics and Chemistry of Solids",
      "year": 2025,
      "doi": "10.1016/j.jpcs.2025.112877",
      "type": "Journal article",
      "volume": "207",
      "issue": "",
      "articleNumber": "112877",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105006487858?origin=resultslist",
      "tags": [
        "2D perovskite",
        "DJ phase",
        "RP phase",
        "SCAPS 1D"
      ],
      "sourceRow": 316
    },
    {
      "title": "TCAD study of CIGS/CZTS double absorber solar cells for high-efficiency photovoltaic applications",
      "authors": "Bhattarai S.; Shrivastav N.; Saikia L.; Kalita P.K.; Reddy M.S.; Radhika S.; Madan J.; Pandey R.",
      "bibtexAuthors": "Bhattarai, Sagar and Shrivastav, Nikhil and Saikia, Lakshi and Kalita, P.K. and Reddy, M. Sudhakara and Radhika, S. and Madan, Jaya and Pandey, Rahul",
      "journal": "Journal of Optics (India)",
      "year": 2025,
      "doi": "10.1007/s12596-025-02769-6",
      "type": "Journal article",
      "volume": "",
      "issue": "",
      "articleNumber": "",
      "pages": "",
      "publicationStage": "Article in press",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105006805207?origin=resultslist",
      "tags": [
        "CZTS/CIGS",
        "SCAPS-1D",
        "Solar cells",
        "TCAD"
      ],
      "sourceRow": 143
    },
    {
      "title": "Temperature-Induced Variations in the Optoelectronic and Impedance Responses of Bandgap-Engineered BaZrS3 Chalcogenide Perovskite Solar Cells: A Numerical Study",
      "authors": "Kumar S.; Gahlawat D.; Kaur J.; Rani U.; Madan J.; Pandey R.; Basu R.",
      "bibtexAuthors": "Kumar, Surender and Gahlawat, Devansh and Kaur, Jaspinder and Rani, Uma and Madan, Jaya and Pandey, Rahul and Basu, Rikmantra",
      "journal": "Journal of Inorganic and Organometallic Polymers and Materials",
      "year": 2025,
      "doi": "10.1007/s10904-025-03932-z",
      "type": "Journal article",
      "volume": "35",
      "issue": "12",
      "articleNumber": "",
      "pages": "10320–10345",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105009604355?origin=resultslist",
      "tags": [
        "Bandgap engineering",
        "Impedance spectroscopy",
        "SCAPS-1D",
        "Transmission loss",
        "Voltage profiling"
      ],
      "sourceRow": 95
    },
    {
      "title": "Theoretical and Numerical Insights into Ba(Hf 1–xZrx)S3Perovskites: Bandgap Tuning and Device-Level Simulation for Efficient Solar Cells",
      "authors": "Gahlawat D.; Kaur J.; Basu R.; Sharma A.K.; Rani U.; Madan J.; Pandey R.",
      "bibtexAuthors": "Gahlawat, Devansh and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Rani, Uma and Madan, Jaya and Pandey, Rahul",
      "journal": "ACS Applied Optical Materials",
      "year": 2025,
      "doi": "10.1021/acsaom.5c00267",
      "type": "Journal article",
      "volume": "3",
      "issue": "9",
      "articleNumber": "",
      "pages": "2129–2152",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, New Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105017128822?origin=resultslist",
      "tags": [
        "activation energy",
        "characteristic time constant",
        "charge-transfer resistance",
        "impedance spectroscopy",
        "SCAPS-1D"
      ],
      "sourceRow": 217
    },
    {
      "title": "Toward high-efficiency photovoltaics: MASnI3 and FASnI3 double absorber perovskite solar cells with optimized conversion efficiency of 28 %",
      "authors": "Panda P.; Kaur J.; Basu R.; Sharma A.K.; Madan J.; Pandey R.",
      "bibtexAuthors": "Panda, Pratyush and Kaur, Jaspinder and Basu, Rikmantra and Sharma, Ajay Kumar and Madan, Jaya and Pandey, Rahul",
      "journal": "Physica B: Condensed Matter",
      "year": 2025,
      "doi": "10.1016/j.physb.2025.417232",
      "type": "Journal article",
      "volume": "710",
      "issue": "",
      "articleNumber": "417232",
      "pages": "",
      "publicationStage": "Final",
      "nitDelhiAffiliation": true,
      "authorAffiliation": "Pandey R., Department of Applied Sciences (Physics), National Institute of Technology Delhi, Delhi, 110036, India",
      "url": "https://www.scopus.com/pages/publications/105002563996?origin=resultslist",
      "tags": [
        "Double absorber solar cell",
        "FASnI<sub>3</sub>",
        "Lead-free perovskites",
        "MASnI<sub>3</sub>",
        "Photovoltaic efficiency optimization"
      ],
      "sourceRow": 83
    }
  ],
  "members": [],
  "news": [
    {
      "source": "linkedin",
      "category": "Events",
      "title": "Dr. Rahul Pandey moderates Solar Cell Technology panel at REconnect 2026",
      "date": "2026-05-21",
      "dateLabel": "21–22 May 2026 (event dates)",
      "summary": "Dr. Rahul Pandey moderated the Solar Cell Technology panel at the third REconnect Annual Flagship Summit & Expo, organised by Energetica India Magazine at The Grand New Delhi. The LinkedIn update shares his reflections on the event.",
      "linkedinUrl": "https://www.linkedin.com/feed/update/urn:li:activity:7507443092518572032/",
      "image": "assets/reconnect-2026-rahul-pandey.jpg",
      "imageAlt": "REconnect Summit graphic featuring Dr. Rahul Pandey, panel moderator for Solar Cell Technology.",
      "tags": [
        "Solar energy",
        "Photovoltaics",
        "Solar cell technology",
        "REconnect Summit",
        "Renewable energy"
      ],
      "sourceAuthor": "REconnect Summit",
      "sharedBy": "Dr. Rahul Pandey",
      "submittedUrl": "https://lnkd.in/p/g79nR3av",
      "dateBasis": "Event dates stated in the post; the LinkedIn posting date was not verified.",
      "linkedinEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7507428564988968960",
      "embedHeight": 1100,
      "displayOrder": 2
    },
    {
      "source": "linkedin",
      "category": "Awards",
      "title": "Stanford/Elsevier Top 2% Scientists recognition — 2026",
      "summary": "Dr. Rahul Pandey shares his inclusion in the Stanford/Elsevier Top 2% Scientists List 2026 and acknowledges the research scholars and collaborators who contributed to his work.",
      "date": "",
      "dateLabel": "LinkedIn update",
      "linkedinUrl": "https://www.linkedin.com/feed/update/urn:li:activity:7513658893999370240",
      "linkedinEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7513658891927298049",
      "embedHeight": 1070,
      "sourceAuthor": "Dr. Rahul Pandey",
      "tags": [
        "Top 2% Scientists",
        "Stanford",
        "Elsevier",
        "Research recognition"
      ],
      "displayOrder": 1,
      "submittedEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7513658891927298049?collapsed=1",
      "submittedEmbedHeight": 670,
      "dateBasis": "Event dates where explicitly stated; exact LinkedIn publication date not claimed.",
      "image": "assets/linkedin-news-7513658891927298049.jpg",
      "imageAlt": "Image accompanying the LinkedIn post: Stanford/Elsevier Top 2% Scientists recognition — 2026"
    },
    {
      "source": "linkedin",
      "category": "Events",
      "title": "Hands-on SRAM and QuantumATK workshop at NIT Delhi",
      "summary": "NIT Delhi hosted a two-day workshop on high-speed SRAM and atomistic nanoelectronic simulation using Cadence Virtuoso and QuantumATK, in collaboration with Maharishi Markandeshwar Engineering College, Mullana. The post reports participation by more than 130 attendees.",
      "date": "2026-08-27",
      "dateLabel": "27–28 August 2026 (event dates)",
      "linkedinUrl": "https://www.linkedin.com/feed/update/urn:li:activity:7499453323293638656",
      "linkedinEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7499453321972383744",
      "embedHeight": 1000,
      "sourceAuthor": "Dr. Rahul Pandey",
      "tags": [
        "SRAM",
        "Cadence Virtuoso",
        "QuantumATK",
        "Nanoelectronics",
        "Workshop"
      ],
      "displayOrder": 3,
      "submittedEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7499453321972383744?collapsed=1",
      "submittedEmbedHeight": 543,
      "dateBasis": "Event dates where explicitly stated; exact LinkedIn publication date not claimed.",
      "image": "assets/linkedin-news-7499453321972383744.jpg",
      "imageAlt": "Image accompanying the LinkedIn post: Hands-on SRAM and QuantumATK workshop at NIT Delhi"
    },
    {
      "source": "linkedin",
      "category": "Events",
      "title": "REconnect 2026: photovoltaics, industry and panel-discussion highlights",
      "summary": "Dr. Rahul Pandey shares highlights from the REconnect panel discussion on photovoltaic research, industrial solar deployment and collaboration between academia and industry.",
      "date": "2026-05-21",
      "dateLabel": "21–22 May 2026 (event dates)",
      "linkedinUrl": "https://www.linkedin.com/feed/update/urn:li:activity:7465726494498119680",
      "linkedinEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7465726493537583104",
      "embedHeight": 1028,
      "sourceAuthor": "Dr. Rahul Pandey",
      "tags": [
        "REconnect",
        "Photovoltaics",
        "Solar energy",
        "Academia and industry"
      ],
      "displayOrder": 4,
      "submittedEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7465726493537583104?collapsed=1",
      "submittedEmbedHeight": 628,
      "dateBasis": "Event dates where explicitly stated; exact LinkedIn publication date not claimed.",
      "image": "assets/linkedin-news-7465726493537583104.jpg",
      "imageAlt": "Image accompanying the LinkedIn post: REconnect 2026: photovoltaics, industry and panel-discussion highlights"
    },
    {
      "source": "linkedin",
      "category": "Events",
      "title": "REconnect 2026 speaker announcement: Innovation in Solar Cells",
      "summary": "Dr. Rahul Pandey announced his session on Innovation in Solar Cells & Emerging Technologies at the REconnect Annual Flagship Summit & Expo in New Delhi. The post includes the organiser’s invitation and event information.",
      "date": "2026-05-21",
      "dateLabel": "21–22 May 2026 (event dates)",
      "linkedinUrl": "https://www.linkedin.com/feed/update/urn:li:activity:7461817767269277696",
      "linkedinEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7461817766690344960",
      "embedHeight": 1514,
      "sourceAuthor": "Dr. Rahul Pandey",
      "tags": [
        "REconnect",
        "Solar cells",
        "Emerging technologies",
        "Speaker"
      ],
      "displayOrder": 5,
      "submittedEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7461817766690344960?collapsed=1",
      "submittedEmbedHeight": 1114,
      "dateBasis": "Event dates where explicitly stated; exact LinkedIn publication date not claimed.",
      "image": "assets/linkedin-news-7461817766690344960.jpg",
      "imageAlt": "Image accompanying the LinkedIn post: REconnect 2026 speaker announcement: Innovation in Solar Cells"
    },
    {
      "source": "linkedin",
      "category": "Publications",
      "title": "Lead-free Cs₂AlBiCl₆ perovskite solar cells: synthesis and device modelling",
      "summary": "A publication announcement in IEEE Transactions on Electron Devices describes material synthesis, structural characterisation and device modelling for lead-free Cs₂AlBiCl₆ double-perovskite solar cells.",
      "date": "",
      "dateLabel": "LinkedIn update",
      "linkedinUrl": "https://www.linkedin.com/feed/update/urn:li:activity:7461629356201754624",
      "linkedinEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7461629354943520770",
      "embedHeight": 1070,
      "sourceAuthor": "Dr. Rahul Pandey",
      "tags": [
        "Lead-free perovskite",
        "Cs2AlBiCl6",
        "Photovoltaics",
        "IEEE Transactions on Electron Devices"
      ],
      "displayOrder": 6,
      "submittedEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7461629354943520770?collapsed=1",
      "submittedEmbedHeight": 670,
      "dateBasis": "Event dates where explicitly stated; exact LinkedIn publication date not claimed.",
      "image": "assets/linkedin-news-7461629354943520770.jpg",
      "imageAlt": "Image accompanying the LinkedIn post: Lead-free Cs₂AlBiCl₆ perovskite solar cells: synthesis and device modelling"
    },
    {
      "source": "linkedin",
      "category": "Publications",
      "title": "IGZO thin-film transistor reliability for wearable biosensing",
      "summary": "A publication announcement in IEEE Transactions on Device and Materials Reliability presents a study of bending effects on IGZO thin-film transistors for wearable biosensing applications.",
      "date": "",
      "dateLabel": "LinkedIn update",
      "linkedinUrl": "https://www.linkedin.com/feed/update/urn:li:activity:7451164283343921152",
      "linkedinEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7451164281997271040",
      "embedHeight": 1025,
      "sourceAuthor": "Dr. Rahul Pandey",
      "tags": [
        "IGZO",
        "Thin film transistor",
        "Biosensing",
        "Wearable electronics",
        "IEEE"
      ],
      "displayOrder": 7,
      "submittedEmbedUrl": "https://www.linkedin.com/embed/feed/update/urn:li:share:7451164281997271040?collapsed=1",
      "submittedEmbedHeight": 625,
      "dateBasis": "Event dates where explicitly stated; exact LinkedIn publication date not claimed.",
      "image": "assets/linkedin-news-7451164281997271040.jpg",
      "imageAlt": "Image accompanying the LinkedIn post: IGZO thin-film transistor reliability for wearable biosensing"
    }
  ],
  "events": [],
  "gallery": [],
  "projects": [],
  "publicationImport": {
    "source": "Scopus author export",
    "exportDate": "2026-10-08",
    "authorID": "56609687400",
    "matchRule": "NIT Delhi attached to Dr. Rahul Pandey in Authors with affiliations",
    "publicationStages": {
      "Final": 46,
      "Article in press": 3
    },
    "yearsAsExported": true
  },
  "interns": []
};
