'use strict';
(()=>{
 const root=document.querySelector('#content-editor');if(!root)return;
 const core=window.LAB_EDITOR_CORE,baseline=core.clone(window.LAB_CONTENT),base=core.fingerprint(baseline),storageKey='asmd-lab-draft-v1';
 let data=core.clone(baseline),images={},section='events',editing=-1,dirty=false,uploading=false,stale=null;
 Object.keys(core.schemas).forEach(key=>data[key]??=[]);
 const $=q=>root.querySelector(q),make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 const message=(text,error=false)=>{const target=$('#editor-message');target.textContent=text;target.classList.toggle('is-error',error);};
 function backup(){return {format:'asmd-lab-editor-v1',base,data,images,savedAt:new Date().toISOString()};}
 function persist(){try{localStorage.setItem(storageKey,JSON.stringify(backup()));message('Draft saved in this browser. Download a backup before closing or switching devices.');}catch{message('Changes are kept in memory only. Browser storage is unavailable or full. Download a backup now.',true);}}
 try{const value=localStorage.getItem(storageKey);if(value){const saved=JSON.parse(value);if(saved.base===base){const checked=core.validateBackup(saved,baseline);data=checked.data;images=checked.images;message('Your saved draft has been restored. It has not been uploaded to GitHub.');}else{stale=saved;$('#editor-stale').hidden=false;message('The website has changed since your previous draft. The current website is loaded; download the old draft as a reference.',true);}}}catch{message('A saved draft could not be restored. The current website is loaded.',true);}
 const fileURL=path=>images[path]||window.LAB_ASSETS?.[path]||path;
 function download(blob,name){const url=URL.createObjectURL(blob),a=make('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
 function ordered(){return data[section].map((record,index)=>({record,index})).sort((a,b)=>section==='news'?((a.record.displayOrder??Infinity)-(b.record.displayOrder??Infinity)||String(b.record.date||'').localeCompare(String(a.record.date||''))):0);}
 function renderList(){const list=$('#editor-list');list.replaceChildren();$('#editor-count').textContent=data[section].length+' '+core.schemas[section].label.toLowerCase()+' entries';
  if(!data[section].length){list.append(make('p','No entries yet. Use the form to add the first one.','editor-empty'));return;}
  ordered().forEach(({record,index},order)=>{const card=make('article',null,'editor-entry');const image=record.image||record.photo;if(image){const img=make('img');img.src=fileURL(image);img.alt=record.alt||record.imageAlt||record.name||record.title||record.caption;img.loading='lazy';card.append(img);}
   const info=make('div');info.append(make('h3',record.title||record.name||record.caption),make('p',[record.dateLabel||record.date,record.category,record.status,record.level,record.institution].filter(Boolean).join(' · ')));if(record.summary||record.topic)info.append(make('p',record.summary||record.topic,'editor-summary'));
   const actions=make('div',null,'editor-entry-actions'),edit=make('button','Edit'),remove=make('button','Remove');edit.type=remove.type='button';edit.addEventListener('click',()=>{if(!leaveForm())return;editing=index;renderForm(record);$('#editor-form-heading').focus();});remove.addEventListener('click',()=>{if(!leaveForm()||!confirm('Remove this '+core.schemas[section].singular.toLowerCase()+' from the draft?'))return;data[section].splice(index,1);editing=-1;renderForm();persist();renderList();});actions.append(edit,remove);
   if(section==='news'){const first=make('button',order===0?'Featured first':'Show first');first.type='button';first.disabled=order===0;first.addEventListener('click',()=>{if(!leaveForm())return;record.displayOrder=Math.min(0,...data.news.map(n=>Number.isFinite(n.displayOrder)?n.displayOrder:0))-1;persist();renderList();});actions.append(first);}
   info.append(actions);card.append(info);list.append(card);
  });
 }
 function leaveForm(){if(uploading){message('Wait for the photograph to finish processing.',true);return false;}if(dirty&&!confirm('Discard the unsaved form changes? Choose Cancel and Save entry to keep them.'))return false;dirty=false;return true;}
 function renderForm(record={}){const schema=core.schemas[section],fields=$('#editor-fields');fields.replaceChildren();dirty=false;$('#editor-form-heading').textContent=(editing<0?'Add ':'Edit ')+schema.singular.toLowerCase();$('#editor-save').textContent=editing<0?'Add to draft':'Save entry';
  schema.fields.forEach(field=>{const label=make('label',field.label+(field.required?' *':''),'editor-field'),input=make(field.type==='textarea'?'textarea':field.type==='select'?'select':'input');input.id='editor-field-'+field.key;input.name=field.key;input.required=!!field.required;
   if(field.type==='select'){field.choices.forEach(choice=>{const opt=make('option',choice);opt.value=choice;input.append(opt);});}else if(field.type==='textarea')input.rows=4;else input.type=['date','url','number'].includes(field.type)?field.type:'text';
   if(field.type==='number'){input.min='380';input.max='2400';input.step='1';}
   input.value=field.type==='tags'?(record[field.key]||[]).join(', '):(record[field.key]??(field.type==='select'?field.choices[0]:''));input.addEventListener('input',()=>dirty=true);input.addEventListener('change',()=>dirty=true);label.append(input);
   if(field.type==='image'){input.placeholder='Upload below, or enter an image link';const upload=make('input');upload.type='file';upload.accept='image/jpeg,image/png,image/webp';upload.setAttribute('aria-label','Upload '+field.label.toLowerCase());const preview=make('img',null,'editor-photo-preview');preview.hidden=!input.value;if(input.value)preview.src=fileURL(input.value);preview.alt='Selected image preview';label.append(upload,preview,make('small','JPG, PNG or WebP. Photos are resized for the website.'));
    input.addEventListener('change',()=>{preview.hidden=!input.value||(!core.assetPath(input.value)&&!core.validLink(input.value));if(!preview.hidden)preview.src=fileURL(input.value);});upload.addEventListener('change',async()=>{const file=upload.files[0];if(!file)return;uploading=true;$('#editor-save').disabled=true;message('Preparing photograph…');try{const result=await processPhoto(file);images[result.path]=result.value;input.value=result.path;preview.src=result.value;preview.hidden=false;dirty=true;message('Photograph ready. Save the entry to include it in your draft.');}catch(error){message(error.message,true);}finally{uploading=false;$('#editor-save').disabled=false;upload.value='';}});
   }
   if(field.key==='linkedinEmbedUrl')label.append(make('small','Optional. Paste the embed URL, or use the iframe-code box below. The post can always be shown as a linked card.'));
   fields.append(label);
  });
  if(section==='news'){const label=make('label','LinkedIn iframe code (optional)','editor-field'),input=make('textarea');input.rows=2;input.placeholder='Paste the iframe code copied from LinkedIn';const button=make('button','Use embed code');button.type='button';button.addEventListener('click',()=>{const parsed=new DOMParser().parseFromString(input.value,'text/html'),frames=parsed.querySelectorAll('iframe');const src=frames[0]?.getAttribute('src');if(frames.length!==1||!core.validLink(src,true)){message('Use a single iframe copied from LinkedIn’s Embed this post option.',true);return;}const url=new URL(src);url.searchParams.delete('collapsed');$('#editor-field-linkedinEmbedUrl').value=url.href;const height=Number(frames[0].getAttribute('height'));$('#editor-field-embedHeight').value=Number.isFinite(height)&&height>=380&&height<=2400?height:1000;$('#editor-field-source').value='linkedin';dirty=true;message('Embed details added. Add the direct post link and save the entry.');});label.append(input,button);fields.append(label);}
 }
 async function processPhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('Choose a JPG, PNG or WebP photograph smaller than 20 MB.');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();if(!image.naturalWidth||!image.naturalHeight||image.naturalWidth*image.naturalHeight>50000000)throw Error('This photograph is too large. Resize it before uploading.');const scale=Math.min(1,1600/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);const value=canvas.toDataURL('image/jpeg',.86);if(value.length>4000000)throw Error('The processed photograph is still too large. Use a smaller image.');const token=globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2);return {path:'assets/uploads/'+token+'.jpg',value};}finally{URL.revokeObjectURL(url);}}
 $('#editor-form').addEventListener('submit',event=>{event.preventDefault();if(uploading)return;const old=editing>=0?data[section][editing]:{},record=core.clone(old);for(const field of core.schemas[section].fields){const value=$('#editor-field-'+field.key).value.trim();if(!value){delete record[field.key];continue;}record[field.key]=field.type==='number'?Number(value):field.type==='tags'?value.split(',').map(t=>t.trim()).filter(Boolean):value;}const errors=core.validate(section,record);if(errors.length){message(errors.join(' '),true);return;}if(editing<0){if(section==='news')record.displayOrder=Math.min(0,...data.news.map(n=>Number.isFinite(n.displayOrder)?n.displayOrder:0))-1;data[section].push(record);}else data[section][editing]=record;editing=-1;dirty=false;renderForm();renderList();persist();});
 const tabs=$('#editor-tabs');Object.entries(core.schemas).forEach(([key,schema])=>{const button=make('button',schema.label);button.type='button';button.dataset.section=key;button.setAttribute('aria-pressed',String(key===section));button.addEventListener('click',()=>{if(!leaveForm())return;section=key;editing=-1;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.section===section)));renderForm();renderList();});tabs.append(button);});
 $('#editor-cancel').addEventListener('click',()=>{if(!leaveForm())return;editing=-1;renderForm();});
 $('#editor-backup').addEventListener('click',()=>{if(dirty||uploading){message('Save the open form before downloading your backup.',true);return;}download(new Blob([JSON.stringify(backup(),null,2)],{type:'application/json'}),'ASMD_Lab_Draft_Backup.json');});
 $('#editor-stale-download').addEventListener('click',()=>download(new Blob([JSON.stringify(stale,null,2)],{type:'application/json'}),'ASMD_Lab_Previous_Draft.json'));
 $('#editor-import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>25*1024*1024)throw Error('Backup must be smaller than 25 MB.');const checked=core.validateBackup(JSON.parse(await file.text()),baseline);if(!leaveForm()||!confirm('Replace the current draft with this backup?'))return;data=checked.data;images=checked.images;editing=-1;renderForm();renderList();persist();}catch(error){message(error.message,true);}finally{event.target.value='';}});
 $('#editor-reset').addEventListener('click',()=>{if(!leaveForm()||!confirm('Discard all draft changes and reload the website’s saved content? Download a backup first if needed.'))return;data=core.clone(baseline);Object.keys(core.schemas).forEach(k=>data[k]??=[]);images={};editing=-1;stale=null;$('#editor-stale').hidden=true;renderForm();renderList();persist();});
 $('#editor-export').addEventListener('click',()=>{if(dirty||uploading){message('Save the open form before downloading your updates.',true);return;}try{for(const kind of Object.keys(core.schemas))for(const record of data[kind]){const errors=core.validate(kind,record);if(errors.length)throw Error(core.schemas[kind].label+': '+errors.join(' '));}const exported=core.clone(data);exported.updated=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});download(core.zip(core.packageFiles(exported,images)),'ASMD_Lab_Updates.zip');message('Update package downloaded. Extract it, then upload content.js and the assets folder to GitHub. This download has not changed the repository.');$('#editor-publish-steps').hidden=false;}catch(error){message(error.message,true);}});
 addEventListener('beforeunload',event=>{if(dirty||uploading){event.preventDefault();event.returnValue='';}});
 renderForm();renderList();
})();
